import test from 'node:test';
import assert from 'node:assert/strict';
import {Engine} from '../src/core/engine';
import {WEAPON_IDS,WEAPONS,PASSIVE_IDS,RULES,CLASSES,CLASS_IDS,BOSSES,reduction,weaponStats,targetPopulation,type WeaponId} from '../src/core/config';
import {freshProfile,runConfig,defaultPreset,purchase,MASTERY_IDS,type MasteryId} from '../src/core/meta';
import {freshSave,decodeSave,checkpoint,readSave,writeSave} from '../src/core/storage';
import {choices} from '../src/core/upgrades';
import {Random} from '../src/core/random';
import {xpForLevel} from '../src/core/config';
import {goldReward,fragmentReward} from '../src/core/economy';
import {permanentCost,masteryCost} from '../src/core/meta';
function arena(id:WeaponId='longsword',lv=1){const p=freshProfile();p.weapons=[...WEAPON_IDS];p.passives=[...PASSIVE_IDS];p.presets=[{...defaultPreset(WEAPONS[id].class==='all'?'warrior':WEAPONS[id].class as 'warrior'|'mage'|'archer'),startWeapon:id,weapons:[...WEAPON_IDS],passives:[...PASSIVE_IDS]}];const e=new Engine(123,runConfig(p));e.enemies=[];e.build.weapons[id]=lv;e.player.invulnerable=1e6;return e;}
function step(e:Engine,n=100){for(let i=0;i<n;i++){if(e.status==='upgrade')e.selectUpgrade(0);e.step(.05,{x:0,y:0});e.drainEvents();}}
for(const id of WEAPON_IDS)for(const lv of [1,3,5,8])test(`${id} level ${lv} deals real damage`,()=>{const e=arena(id,lv);const s=weaponStats(id,lv);for(let i=0;i<10;i++){const a=i/10*Math.PI*2,r=WEAPONS[id].kind==='orbit'?s.range:60;const t=e.spawn('brute',e.player.x+Math.cos(a)*r,e.player.y+Math.sin(a)*r)!;t.hp=t.maxHp=1e7;t.speed=0;t.damage=0;}step(e,110);assert.ok(e.weaponDamage[id]>0,`${id} did not hit`);assert.ok(e.projectiles.every(p=>p.enemy===false));});
test('Opening enemies start beyond the camera and no one-hit starter kills',()=>{const e=new Engine(1);assert.equal(e.enemies.length,RULES.openingCount);assert.ok(e.enemies.some(x=>x.kind==='crawler'));assert.ok(e.enemies.every(x=>Math.hypot(x.x-e.player.x,x.y-e.player.y)>=RULES.openingRadius-1));const t=e.enemies.find(x=>x.kind==='hollow')!;e.rng.next=()=>.99;e.hit(t,WEAPONS.longsword.damage,'longsword');assert.ok(t.hp>0);assert.equal(targetPopulation(480),140);});
test('All classes have distinct HP, defense, speed and weapon',()=>{for(const id of CLASS_IDS){const p=freshProfile();p.presets=[defaultPreset(id)];const e=new Engine(1,runConfig(p));assert.equal(e.player.hp,CLASSES[id].hp);assert.equal(e.defense,CLASSES[id].defense);assert.equal(e.playerSpeed,CLASSES[id].speed);assert.equal(WEAPONS[e.config.startWeapon].class,id);}});
test('Every passive upgrades to cap and changes its designated stat or effect',()=>{const e=arena();const before={damage:e.damageMultiplier,speed:e.playerSpeed,haste:e.attackSpeed,range:e.rangeMultiplier,hp:e.player.maxHp,def:e.defense,crit:e.criticalChance,critD:e.criticalDamage,pickup:e.pickupRadius};for(const id of PASSIVE_IDS){e.build.passives=Object.fromEntries(PASSIVE_IDS.map(k=>[k,0])) as typeof e.build.passives;for(let i=0;i<9;i++)e.applyUpgrade({id,rarity:'common',bonus:0});assert.equal(e.build.passives[id],8);if(id==='power')assert.ok(e.damageMultiplier>before.damage);if(id==='speed')assert.ok(e.playerSpeed>before.speed);if(id==='haste')assert.ok(e.attackSpeed>before.haste);if(id==='reach')assert.ok(e.rangeMultiplier>before.range);if(id==='vitality')assert.ok(e.player.maxHp>before.hp);if(id==='armor')assert.ok(e.defense>before.def);if(id==='crit')assert.ok(e.criticalChance>before.crit);if(id==='ferocity')assert.ok(e.criticalDamage>before.critD);if(id==='magnet')assert.ok(e.pickupRadius>before.pickup);if(id==='regen'){e.player.hp=10;step(e,20);assert.ok(e.player.hp>11);}if(id==='leech'){e.player.hp=10;step(e,20);const t=e.spawn('brute',e.player.x+60,e.player.y)!;e.hit(t,1,'longsword');assert.ok(e.player.hp>10);}}});
test('Slot limits and curated pools constrain offers and direct acquisition',()=>{const e=arena();for(const id of WEAPON_IDS.slice(0,8))e.build.weapons[id]=1; // reset starter so exactly eight
for(const id of WEAPON_IDS.slice(8))e.build.weapons[id]=0;for(const id of PASSIVE_IDS.slice(0,8))e.build.passives[id]=1;for(let i=0;i<100;i++)for(const o of choices(e.build,e.rng,e.config))if(!o.recovery)assert.ok(o.id in e.build.weapons?e.build.weapons[o.id as WeaponId]>0:e.build.passives[o.id as keyof typeof e.build.passives]>0);e.applyUpgrade({id:'hammer',rarity:'common',bonus:0});assert.equal(e.build.weapons.hammer,0);});
test('Completed builds auto-progress without 160 more pauses',()=>{const e=arena();e.config.weapons=['longsword'];e.config.passives=['power'];e.build.weapons.longsword=8;e.build.passives.power=8;e.addXp(999);assert.equal(e.status,'playing');assert.equal(e.masteryPower,1);});
test('Pause, normalized movement, dash cooldown, collision, death and retirement',()=>{const e=arena();e.player.invulnerable=0;const x=e.player.x,y=e.player.y;e.step(.05,{x:1,y:1});assert.ok(Math.abs(Math.hypot(e.player.x-x,e.player.y-y)-e.playerSpeed*.05)<.01);e.pause();const t=e.time;e.step(.05,{x:1,y:0});assert.equal(e.time,t);e.pause();e.step(.05,{x:1,y:0,dash:true});assert.ok(e.player.dashCooldown>7);e.player.invulnerable=0;e.player.dashLeft=0;e.spawn('brute',e.player.x,e.player.y);const hp=e.player.hp;e.step(.05,{x:0,y:0});assert.ok(e.player.hp<hp);e.player.invulnerable=0;e.hurt(1e9);assert.equal(e.status,'dead');const fresh=arena();fresh.retire();assert.equal(fresh.status,'retired');});
test('DEF cannot grant immunity',()=>{assert.equal(reduction(0),0);assert.equal(reduction(100),.5);assert.equal(reduction(1e8),.7);});
test('Preserved boss AI has no hostile projectiles when spawned explicitly',()=>{const e=arena();for(let i=0;i<3;i++){e.enemies=[];e.time=(i+1)*340-.01;e.spawn(BOSSES[i]);e.step(.05,{x:0,y:0});assert.equal(e.boss?.kind,BOSSES[i]);const b=e.boss!;b.x=e.player.x+180;b.y=e.player.y;b.attack=0;step(e,3);assert.ok(e.projectiles.every(p=>!p.enemy));e.hit(b,1e9,'longsword');assert.equal(e.bossKills,i+1);assert.equal(e.souls,(i+1)*3);assert.notEqual(e.status,'retired');assert.notEqual(e.status,'dead');}});
test('Boss stamp cancels when its source dies',()=>{const e=arena();const b=e.spawn('boss',e.player.x+100,e.player.y)!;b.attack=0;step(e,1);assert.ok(e.warnings.length);e.hit(b,1e9,'longsword');step(e,1);assert.equal(e.warnings.length,0);});
test('Summoner creates melee children without fragment rewards',()=>{const e=arena();const s=e.spawn('seer',e.player.x+200,e.player.y)!;s.attack=0;step(e,1);const child=e.enemies.find(x=>x.summoned)!;assert.ok(child);e.hit(child,999,'longsword');assert.equal(e.souls,0);assert.equal(e.gold,0);});
test('Bleed, burn and poison deal damage after the hit; frost slows',()=>{for(const id of ['dual','firestaff','poisonbow','froststaff'] as const){const e=arena(id);const t=e.spawn('brute',e.player.x+100,e.player.y)!;t.speed=0;e.hit(t,1,id);assert.ok(id==='froststaff'?t.slow>0:Object.keys(t.dots).length>0);if(id!=='froststaff'){const hp=t.hp;for(const k of WEAPON_IDS)e.build.weapons[k]=0;step(e,10);assert.ok(t.hp<hp);}}});
test('Catalyst explosion has one generation, fortune changes gold',()=>{const e=arena('fire');e.build.passives.catalyst=8;e.build.passives.fortune=8;const a=e.spawn('hollow',e.player.x+60,e.player.y)!,b=e.spawn('brute',e.player.x+70,e.player.y)!;e.grid.rebuild(e.enemies);e.hit(a,999,'fire');assert.ok(b.hp<b.maxHp);assert.ok(e.gold>.25);assert.ok(e.events.length<20);});
test('Purchases enforce cost, caps and class masteries',()=>{const p=freshProfile();assert.equal(purchase(p,'weapon','hammer'),false);p.gold=1e6;p.souls=1e6;assert.equal(purchase(p,'weapon','hammer'),true);assert.equal(purchase(p,'weapon','hammer'),false);for(let i=0;i<20;i++)purchase(p,'permanent','attack');assert.equal(p.permanent.attack,10);for(const id of MASTERY_IDS){for(let i=0;i<7;i++)purchase(p,'mastery',id);assert.equal(p.masteries[id],5);}assert.equal(purchase(p,'weapon','__proto__'),false);});
test('All nine mastery branches have measurable effects',()=>{for(const id of MASTERY_IDS){const cls=id==='berserker'||id==='guardian'||id==='soulwarrior'?'warrior':id==='inferno'||id==='storm'||id==='arcane'?'mage':'archer';const p=freshProfile();p.presets=[defaultPreset(cls)];p.masteries[id]=5;p.presets[0].masteries=[id];const e=new Engine(1,runConfig(p));assert.equal(e.mastery(id),5);if(id==='guardian')assert.equal(e.defense,34);if(id==='soulwarrior')assert.equal(e.dashCooldown,6.5);if(id==='storm')assert.equal(e.attackSpeed,1.25);if(id==='soulhunter')assert.ok(e.pickupRadius>120);if(id==='berserker'){e.rage=1;assert.equal(e.damageMultiplier,1.6);} }});
test('Snapshot roundtrip preserves exact combat, pending cards and seeded RNG',()=>{const e=arena('fire',8);step(e,12);e.addXp(100);const v=e.snapshot(),r=Engine.restore(JSON.parse(JSON.stringify(v)))!;assert.ok(r);assert.equal(r.status,e.status);assert.deepEqual(r.offers,e.offers);assert.equal(r.rng.next(),e.rng.next());assert.deepEqual(r.build,e.build);assert.equal(r.time,e.time);assert.ok(r.projectiles.every(p=>p.hit instanceof Set));});
test('Checkpoint ledger stays idempotent and the old time-based difficulty unlock is disabled',()=>{const s=freshSave(),e=arena();e.gold=123.9;e.souls=4;e.time=1800;e.nextBoss=1920;checkpoint(s,e);assert.equal(s.profile.gold,123);const r=Engine.restore(s.run)!;checkpoint(s,r);assert.equal(s.profile.gold,123);assert.equal(s.profile.souls,4);assert.equal(s.profile.unlockedDifficulty,0);r.gold+=1.2;checkpoint(s,r);assert.equal(s.profile.gold,125);r.retire();checkpoint(s,r,true);assert.equal(s.run,null);assert.equal(s.stats.runs,1);});
test('Corrupt saves recover and v1 migrates without altering historical stats',()=>{assert.deepEqual(decodeSave('{'),freshSave());const old=decodeSave(JSON.stringify({version:1,settings:{volume:.2},stats:{runs:12,wins:3,kills:42}}));assert.equal(old.stats.runs,12);assert.equal(old.stats.wins,3);assert.equal(old.settings.volume,.2);assert.equal(old.profile.gold,0);const v=freshSave();v.run={bad:true};assert.equal(decodeSave(JSON.stringify(v)).run,null);assert.equal(Engine.restore({...arena().snapshot(),time:NaN}),undefined);});
test('RNG stays uint32 and damage simulation has finite bounded state at 3 hours',()=>{const r=new Random(1);for(let i=0;i<1e5;i++)r.next();assert.ok(r.seed<=0xffffffff);const e=arena('scatterbow',8);e.time=10800;e.nextBoss=11040;for(let i=0;i<300;i++)e.spawn();step(e,300);assert.ok(e.enemies.length<=300);assert.ok(e.loot.length<=380);assert.ok(e.projectiles.length<1000);assert.ok(Number.isFinite(e.damageDealt));assert.ok(Engine.restore(e.snapshot()));});
test('Inferno, overload, marks, barrage and soul collection execute their combat effects',()=>{
 const setup=(cls:'mage'|'archer',id:MasteryId,start:WeaponId)=>{const p=freshProfile();p.presets=[{...defaultPreset(cls),startWeapon:start}];p.masteries[id]=5;p.presets[0].masteries=[id];const e=new Engine(8,runConfig(p));e.enemies=[];e.player.invulnerable=100;const t=e.spawn('brute',e.player.x+100,e.player.y)!;t.hp=t.maxHp=10000;t.speed=0;return{e,t};};
 const fire=setup('mage','inferno','firestaff');fire.e.hit(fire.t,1,'firestaff');assert.ok(fire.t.dots.burn!.dps>WEAPONS.firestaff.damage*.2*1.15*1.7);
 const arc=setup('mage','arcane','firestaff');arc.e.casts=5;arc.e.cooldowns.firestaff=0;arc.e.step(.05,{x:0,y:0});assert.ok(arc.e.projectiles[0].damage>=WEAPONS.firestaff.damage*2.39);
 const marks=setup('archer','precision','hunting');marks.t.marks=3;marks.e.rng.next=()=>.20;marks.e.hit(marks.t,10,'hunting');assert.equal(marks.e.events.find(x=>x.type==='hit')?.crit,true);
 const arrows=setup('archer','barrage','hunting');arrows.e.cooldowns.hunting=0;arrows.e.step(.05,{x:0,y:0});assert.equal(arrows.e.projectiles.length,2);
 const souls=setup('archer','soulhunter','hunting');souls.e.drop(souls.e.player.x,souls.e.player.y,5,false);souls.e.step(.05,{x:0,y:0});assert.equal(souls.e.xp,6.5);
});
test('Restoring a playing run reproduces subsequent frames and rewards deterministically',()=>{const e=arena('firestaff',8);step(e,20);const r=Engine.restore(e.snapshot())!;assert.ok(r);r.pause();e.drainEvents();for(let i=0;i<100;i++){if(e.status==='upgrade'){e.selectUpgrade(0);r.selectUpgrade(0);}e.step(.05,{x:.4,y:.9});r.step(.05,{x:.4,y:.9});e.drainEvents();r.drainEvents();}assert.deepEqual(r.snapshot(),e.snapshot());});
test('Malformed player, projectile, mastery or offer fields invalidate only the run',()=>{for(const mutate of [(v:any)=>delete v.player.hp,(v:any)=>delete v.config.permanent.health,(v:any)=>{v.projectiles=[{weapon:'fire',hit:[]}];},(v:any)=>{v.status='upgrade';v.offers=[null,null,null];}]){const v=arena().snapshot();mutate(v);assert.equal(Engine.restore(v),undefined);}});
test('Rendering caps cannot remove projectile damage; orbit hits are time-gated',()=>{const e=arena('orb',8);const s=weaponStats('orb',8),o=e.orbPositions()[0],t=e.spawn('brute',o.x,o.y)!;t.speed=0;t.hp=t.maxHp=10000;e.step(.01,{x:0,y:0});const damage=e.weaponDamage.orb;e.step(.01,{x:0,y:0});assert.equal(e.weaponDamage.orb,damage);const f=arena('scatterbow',8);for(let i=0;i<400;i++)f.projectiles.push({id:10000+i,x:f.player.x,y:f.player.y,vx:0,vy:0,damage:1,enemy:false,life:1,radius:7,target:0,pierce:0,hit:new Set(),weapon:'scatterbow'});const victim=f.spawn('brute',f.player.x,f.player.y)!;victim.hp=victim.maxHp=10000;f.step(.01,{x:0,y:0});assert.ok(f.weaponDamage.scatterbow>=400);});

test('Unavailable LocalStorage degrades to a playable fresh session',()=>{const old=Object.getOwnPropertyDescriptor(globalThis,'localStorage');try{Object.defineProperty(globalThis,'localStorage',{configurable:true,get(){throw new Error('Storage denied');}});assert.deepEqual(readSave(),freshSave());assert.equal(writeSave(freshSave()),false);}finally{if(old)Object.defineProperty(globalThis,'localStorage',old);else delete (globalThis as any).localStorage;}});

test('XP overflow is banked and cards cannot interrupt more often than every 20 combat seconds',()=>{
 const e=arena();e.spawn=()=>undefined;const amount=10000;e.addXp(amount);assert.equal(e.level,2);e.selectUpgrade(0);assert.equal(e.status,'playing');
 const remaining=amount-xpForLevel(1);assert.equal(e.xp,remaining);e.pause();e.step(.05,{x:0,y:0});assert.equal(e.time,0);e.pause();
 for(let i=0;i<399;i++)e.step(.05,{x:0,y:0});assert.equal(e.level,2);assert.equal(e.status,'playing');
 e.step(.05,{x:0,y:0});assert.equal(e.status,'upgrade');assert.equal(e.level,3);assert.equal(e.xp,remaining-xpForLevel(2));
 const restored=Engine.restore(e.snapshot())!;restored.selectUpgrade(0);assert.equal(restored.nextChoiceAt,restored.time+RULES.choiceInterval);
});
test('Every available mixed pool offers a weapon and a passive, with distinct normal cards',()=>{
 const e=arena();for(let i=0;i<300;i++){const offers=choices(e.build,e.rng,e.config);assert.ok(offers.some(o=>o.id in WEAPONS));assert.ok(offers.some(o=>PASSIVE_IDS.includes(o.id as any)));assert.equal(new Set(offers.map(o=>o.id)).size,3);}
 e.config.passives=[];for(const o of choices(e.build,e.rng,e.config))assert.ok(o.id in WEAPONS);
});
test('Eight ranks retain maximum weapon stats and reject a ninth rank',()=>{
 const e=arena();for(const id of e.config.weapons){const max=weaponStats(id,8);assert.equal(max.damage,WEAPONS[id].damage*3.2);assert.equal(max.cooldown,WEAPONS[id].cooldown/1.715);assert.equal(max.finisher,true);}
 for(let i=0;i<20;i++)e.applyUpgrade({id:'longsword',rarity:'common',bonus:0});assert.equal(e.build.weapons.longsword,8);
});
test('V2 profiles retain resources while incompatible Endless runs are not imported',()=>{
 const save=freshSave(),e=arena('longsword',8);save.profile.gold=151;save.profile.souls=3;save.stats.runs=7;
 const legacy:any={...save,version:2,run:e.snapshot()};legacy.run.balanceVersion=3;legacy.run.build.weapons.longsword=12;
 const raw=JSON.stringify(legacy),decoded=decodeSave(raw);assert.equal(decoded.run,null);assert.equal(decoded.profile.gold,151);assert.equal(decoded.profile.souls,3);assert.equal(decoded.stats.runs,7);assert.equal(decoded.version,3);assert.equal(JSON.stringify(legacy),raw);
 assert.equal(Engine.restore(legacy.run),undefined);const invalid=e.snapshot();invalid.build.weapons.longsword=9;assert.equal(Engine.restore(invalid),undefined);
});
test('Economy offers an affordable first purchase and bounded boss fragment growth',()=>{
 assert.equal(goldReward('hollow',0,0),1);assert.equal(goldReward('crawler',0,0,8,10,true),0);
 assert.equal(goldReward('boss',240,0),120);assert.equal(fragmentReward(240,0),3);assert.equal(fragmentReward(10800,0),7);
 assert.deepEqual([0,1,2,3,4].map(masteryCost),[3,5,8,12,18]);assert.deepEqual([0,1,2,3].map(permanentCost),[75,150,255,390]);
 const p=freshProfile();p.gold=120;p.souls=3;assert.ok(purchase(p,'weapon','fire'));assert.equal(p.gold,0);assert.ok(purchase(p,'mastery','guardian'));assert.equal(p.souls,0);
 for(let i=1;i<10;i++)assert.ok(permanentCost(i)>permanentCost(i-1));
});
test('Random spawns remain distant at every arena edge and corner',()=>{
 const e=arena();for(const [x,y] of [[18,18],[3182,18],[18,2382],[3182,2382],[1600,18],[1600,2382],[18,1200],[3182,1200]]){
  e.player.x=x;e.player.y=y;for(let i=0;i<50;i++){e.enemies=[];const enemy=e.spawn('hollow')!;assert.ok(Math.hypot(enemy.x-x,enemy.y-y)>=RULES.openingRadius-1);assert.ok(enemy.x>=40&&enemy.x<=3160&&enemy.y>=40&&enemy.y<=2360);}
 }
});
test('Population pressure grows continuously instead of jumping at minute boundaries',()=>{
 let previous=targetPopulation(0);for(let t=1;t<=3600;t++){const next=targetPopulation(t);assert.ok(next>=previous&&next-previous<=1);previous=next;}assert.equal(previous,260);
});
test('An open V2 card selection cannot become an incompatible V3 run',()=>{
 const e=arena();e.addXp(40);const old=e.snapshot();old.balanceVersion=3;const raw=JSON.stringify({...freshSave(),version:2,run:old});const decoded=decodeSave(raw);assert.equal(decoded.run,null);assert.equal(Engine.restore(old),undefined);
});
