import {freshProfile,normalizePreset,PERMANENT,MASTERY_IDS,type Profile,type PermanentId} from './meta';
import {WEAPON_IDS,PASSIVE_IDS} from './config';
import {Engine} from './engine';
export interface Settings {volume:number;shake:boolean;numbers:boolean;particles:boolean}
export interface Save {version:2;settings:Settings;stats:{runs:number;wins:number;kills:number;bestTime:number;bestLevel:number;bosses:number;retired:number};profile:Profile;run:unknown|null;history:{className:string;time:number;kills:number;bosses:number;gold:number;souls:number;difficulty:number;ending:string}[]}
export const SAVE_KEY='eclipse-survivor-v2';
export const freshSave=():Save=>({version:2,settings:{volume:.35,shake:true,numbers:true,particles:true},stats:{runs:0,wins:0,kills:0,bestTime:0,bestLevel:1,bosses:0,retired:0},profile:freshProfile(),run:null,history:[]});
const num=(v:unknown,f=0,max=1e10)=>typeof v==='number'&&Number.isFinite(v)&&v>=0?Math.min(v,max):f;
export function decodeSave(raw:string|null):Save {const out=freshSave();try{if(!raw)return out;const v=JSON.parse(raw);if(!v||![1,2].includes(v.version))return out;const s=v.settings??{};out.settings={volume:num(s.volume,.35,1),shake:typeof s.shake==='boolean'?s.shake:true,numbers:typeof s.numbers==='boolean'?s.numbers:true,particles:typeof s.particles==='boolean'?s.particles:true};for(const k of Object.keys(out.stats) as (keyof Save['stats'])[])out.stats[k]=num(v.stats?.[k],out.stats[k]);if(v.version===1)return out;
 const p=v.profile??{},base=out.profile;base.gold=num(p.gold);base.souls=Math.floor(num(p.souls));base.weapons=[...new Set([...base.weapons,...(Array.isArray(p.weapons)?p.weapons.filter((id:any)=>WEAPON_IDS.includes(id)):[])])];base.passives=[...new Set([...base.passives,...(Array.isArray(p.passives)?p.passives.filter((id:any)=>PASSIVE_IDS.includes(id)):[])])];for(const id of Object.keys(PERMANENT) as PermanentId[])base.permanent[id]=Math.floor(num(p.permanent?.[id],0,10));for(const id of MASTERY_IDS)base.masteries[id]=Math.floor(num(p.masteries?.[id],0,5));base.unlockedDifficulty=Math.floor(num(p.unlockedDifficulty,0,4));base.difficulty=Math.floor(num(p.difficulty,0,base.unlockedDifficulty));if(Array.isArray(p.presets)&&p.presets.length)base.presets=p.presets.slice(0,12).map((b:any)=>normalizePreset(b??{},base));base.selected=Math.floor(num(p.selected,0,base.presets.length-1));
 out.run=Engine.restore(v.run)?.snapshot()??null;
 if(Array.isArray(v.history))out.history=v.history.slice(0,20).filter((h:any)=>h&&typeof h.className==='string'&&typeof h.ending==='string').map((h:any)=>({className:h.className.slice(0,40),ending:h.ending.slice(0,20),time:num(h.time),kills:num(h.kills),bosses:num(h.bosses),gold:num(h.gold),souls:num(h.souls),difficulty:Math.floor(num(h.difficulty,0,4))}));return out;
 }catch{return out;}}
export function readSave():Save{try{return decodeSave(localStorage.getItem(SAVE_KEY)??localStorage.getItem('eclipse-survivor-v1'));}catch{return freshSave();}}
export function writeSave(save:Save):boolean{try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));return true;}catch{return false;}}
/** Profile rewards and matching checkpoint live in a single localStorage write. */
export function checkpoint(save:Save,e:Engine,finished=false){const gold=Math.floor(e.gold),souls=Math.floor(e.souls);save.profile.gold+=Math.max(0,gold-e.creditedGold);save.profile.souls+=Math.max(0,souls-e.creditedSouls);e.creditedGold=gold;e.creditedSouls=souls;
 if(e.time>=1800)save.profile.unlockedDifficulty=Math.max(save.profile.unlockedDifficulty,Math.min(4,e.config.difficulty+1));
 if(finished){save.run=null;save.stats.runs++;save.stats.kills+=e.kills;save.stats.bosses+=e.bossKills;save.stats.retired+=e.status==='retired'?1:0;save.stats.bestTime=Math.max(save.stats.bestTime,e.time);save.stats.bestLevel=Math.max(save.stats.bestLevel,e.level);save.history.unshift({className:e.config.classId,time:e.time,kills:e.kills,bosses:e.bossKills,gold,souls,difficulty:e.config.difficulty,ending:e.status});save.history=save.history.slice(0,20);}else save.run=e.snapshot();}
