import {chromium} from '@playwright/test';
import {mkdirSync,writeFileSync,existsSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import assert from 'node:assert/strict';
const root=process.env.LOCALAPPDATA?join(process.env.LOCALAPPDATA,'ms-playwright'):'';const exe=root&&existsSync(root)?readdirSync(root).filter(x=>/^chromium-/.test(x)).sort().reverse().map(x=>join(root,x,'chrome-win64','chrome.exe')).find(existsSync):undefined;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||exe,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],failed=[],checks=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)failed.push(`${r.status()} ${r.url()}`);});mkdirSync('reports/screenshots',{recursive:true});
const ready=()=>page.waitForFunction(()=>window.__eclipse?.scene?.textures?.exists('mage'));
const close=()=>page.getByRole('button',{name:'Zurück',exact:true}).click();
try{
 await page.goto(`${process.env.BASE_URL||'http://127.0.0.1:5173/'}?qa=1`);await ready();await page.screenshot({path:'reports/screenshots/v21-menu.png'});
 for(const title of ['Steuerung','Chronik','Waffenkammer','Grundwerte','Meisterschaften','Dein Build','Talismane','Ökonomie']){await page.locator(`[data-action=${({'Steuerung':'controls','Chronik':'stats','Waffenkammer':'shop','Grundwerte':'permanent','Meisterschaften':'masteries','Dein Build':'builds','Talismane':'passives','Ökonomie':'economy'})[title]}]`).first().click();assert.ok(await page.locator('[role=dialog]').isVisible());await close();}checks.push('All management pages, passive collection and economy overview open');
 for(const id of ['mage','archer','warrior']){await page.locator(`[data-action=home-class][data-id=${id}]`).click();assert.equal(await page.locator(`[data-action=home-class][data-id=${id}]`).getAttribute('aria-pressed'),'true');}checks.push('Central character selection works');
 await page.getByRole('button',{name:'Einstellungen',exact:true}).click();await page.locator('#volume').fill('0.18');await close();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('eclipse-survivor-v2')).settings.volume),.18);
 await page.getByRole('button',{name:'Charaktere',exact:true}).click();await page.locator('[data-action=class][data-id=mage]').click();await close();assert.ok(await page.locator('.hero-caption,.run-preview').allTextContents().then(t=>t.join(' ')).then(t=>t.includes('Rissmagier')));
 await page.locator('[data-action=builds]').first().click();await page.getByRole('button',{name:'Bearbeiten',exact:true}).click();await page.locator('#build-name').fill('Funken & Eis');await page.locator('#build-start').selectOption('froststaff');await page.getByRole('button',{name:'Als neue Vorlage speichern',exact:true}).click();await close();assert.ok(await page.locator('.hero-caption,.run-preview').allTextContents().then(t=>t.join(' ')).then(t=>t.includes('Funken & Eis')));checks.push('Class selection, preset copy, editing and settings persist');
 await page.locator('[data-action=expedition]').first().click();assert.equal(await page.locator('.difficulty:disabled').count(),4);await page.getByRole('button',{name:'Durchlauf beginnen',exact:true}).click();await page.waitForTimeout(200);
 const x=await page.evaluate(()=>window.__eclipse.engine.player.x);await page.keyboard.down('d');await page.waitForTimeout(500);await page.keyboard.up('d');assert.ok(await page.evaluate(()=>window.__eclipse.engine.player.x)>x+30);await page.keyboard.press('Space');await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>window.__eclipse.engine.player.dashCooldown)>6);
 await page.keyboard.press('Escape');const time=await page.evaluate(()=>window.__eclipse.engine.time);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__eclipse.engine.time),time);await page.getByRole('button',{name:'Speichern & Hauptmenü',exact:true}).click();await page.reload();await ready();await page.getByRole('button',{name:'Runde fortsetzen',exact:true}).click();assert.ok(await page.getByRole('button',{name:'Weiterkämpfen',exact:true}).isVisible());assert.equal(await page.evaluate(()=>window.__eclipse.engine.time),time);await page.getByRole('button',{name:'Weiterkämpfen',exact:true}).click();checks.push('Real movement, dash, pause, full checkpoint and reload');
 await page.evaluate(()=>{const e=window.__eclipse.engine;e.player.invulnerable=1000;e.addXp(40);});await page.waitForTimeout(150);assert.equal(await page.locator('.upgrade-card').count(),3);await page.screenshot({path:'reports/screenshots/v21-upgrades.png'});while(await page.evaluate(()=>window.__eclipse.engine.status==='upgrade'))await page.keyboard.press('Digit1');checks.push('Three level cards and keyboard selection');
 await page.evaluate(()=>{const e=window.__eclipse.engine;e.time=239.99;});await page.waitForTimeout(150);assert.ok(await page.locator('#boss-hud').isVisible());await page.evaluate(()=>{const e=window.__eclipse.engine;e.boss.x=e.player.x+180;e.boss.y=e.player.y;e.boss.attack=0;});await page.waitForTimeout(250);await page.screenshot({path:'reports/screenshots/v21-boss.png'});await page.evaluate(()=>{const e=window.__eclipse.engine;e.hit(e.boss,999999,'froststaff');});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.__eclipse.engine.bossKills),1);assert.ok(await page.evaluate(()=>window.__eclipse.engine.souls)>0);assert.notEqual(await page.evaluate(()=>window.__eclipse.engine.status),'retired');checks.push('Boss telegraph, reward and continuing Endless combat');
 await page.evaluate(()=>{const e=window.__eclipse.engine;e.status='playing';e.player.invulnerable=0;e.hurt(99999);});await page.waitForTimeout(150);assert.ok(await page.getByText('Im Schatten gefallen.',{exact:true}).isVisible());await page.screenshot({path:'reports/screenshots/v21-defeat.png'});await page.getByRole('button',{name:'Zum Hauptmenü',exact:true}).click();checks.push('Death ends and banks exactly one run');
 // Economy UI with explicitly injected QA currency; never affects a real player profile.
 await page.evaluate(()=>{window.__eclipse.save.profile.gold=10000;window.__eclipse.save.profile.souls=30;});await page.getByRole('button',{name:'Waffenkammer',exact:false}).click();await page.locator('[data-type=weapon][data-id=meteorstaff]').click();assert.ok(await page.locator('[data-type=weapon][data-id=meteorstaff]').isDisabled());await close();await page.locator('[data-action=passives]').click();await page.locator('[data-type=passive][data-id=leech]').click();assert.ok(await page.locator('[data-type=passive][data-id=leech]').isDisabled());await close();await page.locator('[data-action=masteries]').click();await page.locator('[data-id=inferno]').click();await close();await page.locator('[data-action=permanent]').click();await page.locator('[data-id=defense]').click();await close();checks.push('Weapon, mastery and permanent purchases via actual buttons');
 await page.getByRole('button',{name:'Spiel starten',exact:true}).click();await page.waitForTimeout(100);
 await page.evaluate(()=>{const e=window.__eclipse.engine;e.player.invulnerable=10000;e.time=3600;e.nextBoss=3840;e.nextFormation=3645;e.config.weapons=['firestaff','froststaff','arcanestaff','stormstaff','meteorstaff','shadowstaff','soulbook','orb'];for(const id of e.config.weapons)e.build.weapons[id]=8;for(let i=0;i<300;i++){const a=i*2.4;const t=e.spawn(i%8===0?'armored':'hollow',e.player.x+Math.cos(a)*(100+i),e.player.y+Math.sin(a)*(100+i));if(t){t.hp=t.maxHp=1e6;}}});
 const perf=await page.evaluate(async()=>{const values=[];let last=performance.now();for(let i=0;i<150;i++)await new Promise(resolve=>requestAnimationFrame(now=>{values.push(now-last);last=now;const e=window.__eclipse.engine;if(e.status==='upgrade')e.selectUpgrade(0);resolve();}));values.sort((a,b)=>a-b);return {medianFrameMs:values[Math.floor(values.length*.5)],p95FrameMs:values[Math.floor(values.length*.95)],objects:window.__eclipse.scene.diagnostics,enemies:window.__eclipse.engine.enemies.length,projectiles:window.__eclipse.engine.projectiles.length};});await page.screenshot({path:'reports/screenshots/v21-combat.png'});checks.push('300-enemy, eight-weapon browser load scenario');
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Runde freiwillig beenden',exact:true}).click();assert.ok(await page.getByText('Die Nacht überlebt.',{exact:true}).isVisible());await page.getByRole('button',{name:'Zum Hauptmenü',exact:true}).click();
 const counts=[];for(let i=0;i<5;i++){await page.evaluate(()=>window.__eclipse.start());await page.waitForTimeout(150);await page.evaluate(()=>{const e=window.__eclipse.engine;e.player.invulnerable=0;e.hurt(99999);});await page.waitForTimeout(100);counts.push(await page.evaluate(()=>window.__eclipse.scene.diagnostics.displayObjects));await page.getByRole('button',{name:'Zum Hauptmenü',exact:true}).click();}assert.ok(Math.max(...counts)-Math.min(...counts)<80);checks.push('Retirement, clean restarts and stable scene object count');
 await page.evaluate(()=>{localStorage.setItem('eclipse-survivor-v2','broken{');});await page.reload();await ready();assert.ok(await page.getByRole('button',{name:'Spiel starten',exact:true}).isVisible());await page.setViewportSize({width:1024,height:768});await page.screenshot({path:'reports/screenshots/v21-small-menu.png'});checks.push('Corrupt save recovery and compact desktop layout');await page.setViewportSize({width:800,height:700});await page.locator('.compact-arena').click();assert.ok(await page.locator('[role=dialog]').isVisible());await close();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'reports/screenshots/v21-narrow-menu.png',fullPage:true});assert.ok(await page.getByRole('button',{name:'Spiel starten',exact:true}).isVisible());checks.push('Arena remains accessible on narrow menus');
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);const report={checks,errors,failed,performance:perf,restartObjects:counts,note:'Chromium SwiftShader. UI controls real; bosses, economy resources and load state injected through development-only QA hook.'};writeFileSync('reports/browser-v21.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
