import {RULES,WEAPONS,WEAPON_IDS,PASSIVES,PASSIVE_IDS,CLASSES,CLASS_IDS,DIFFICULTIES,ENEMIES,MILESTONES,xpForLevel,reduction,weaponStats,type WeaponId,type PassiveId,type ClassId} from './core/config';
import {PERMANENT,MASTERIES,MASTERY_IDS,permanentCost,masteryCost,normalizePreset,defaultPreset,type PermanentId,type MasteryId,type Preset} from './core/meta';
import {ECONOMY_GUIDE,goldReward,fragmentReward} from './core/economy';
import type {Engine} from './core/engine';
import {upgradeDescription} from './core/upgrades';
import type {Save,Settings} from './core/storage';
export const formatTime=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(id:string)=>`<img class="item-icon" src="assets/icon-${id}.png" alt="" draggable="false">`;
const itemIcon=(id:WeaponId|PassiveId)=>icon(id in WEAPONS?WEAPONS[id as WeaponId].icon:PASSIVES[id as PassiveId].icon);
export interface Actions {reward:(i:number)=>void;nextFloor:()=>void;start:()=>void;continue:()=>void;resume:()=>void;pause:()=>void;menu:()=>void;suspend:()=>void;retire:()=>void;upgrade:(i:number)=>void;settings:(s:Settings)=>void;persist:()=>void;buy:(type:string,id:string)=>boolean}
export class UI {
 root=document.querySelector<HTMLElement>('#ui')!;view='menu';private lastHud=0;private toastTimeout?:ReturnType<typeof setTimeout>;private page='';private draft?:Preset;
 constructor(public save:Save,private actions:Actions){
  this.root.addEventListener('click',event=>{const b=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action!;
   if(['start','continue','resume','pause','menu','suspend','retire','nextFloor'].includes(a))(actions as any)[a]();
   if(a==='reward')actions.reward(Number(b.dataset.index));if(a==='upgrade')actions.upgrade(Number(b.dataset.index));if(a==='close-dialog'){if(this.view==='menu')this.menu();else this.root.querySelector('.dialog-layer')?.remove();}
   if(['settings','controls','stats','characters','shop','permanent','masteries','builds','expedition','economy','passives'].includes(a))this.show(a);
   if(a==='buy'){const ok=actions.buy(b.dataset.type!,b.dataset.id!);this.show(this.page);if(!ok)this.toast('Nicht genügend Ressourcen.');}
   if(a==='class'||a==='home-class'){const cls=b.dataset.id as ClassId;let index=this.save.profile.presets.findIndex(p=>p.classId===cls);if(index<0){this.save.profile.presets.push(defaultPreset(cls));index=this.save.profile.presets.length-1;}this.save.profile.selected=index;actions.persist();if(a==='home-class')this.menu();else this.show('characters');}
   if(a==='select-preset'){this.save.profile.selected=Number(b.dataset.index);actions.persist();this.show('builds');}
   if(a==='edit-preset'){this.draft=structuredClone(this.save.profile.presets[Number(b.dataset.index)]);this.editor();}
   if(a==='save-preset'){this.saveDraft();this.save.profile.presets[this.save.profile.selected]=normalizePreset(this.draft!,this.save.profile);actions.persist();this.show('builds');}
   if(a==='copy-preset'&&this.save.profile.presets.length<12){this.saveDraft();this.save.profile.presets.push(normalizePreset(this.draft!,this.save.profile));this.save.profile.selected=this.save.profile.presets.length-1;actions.persist();this.show('builds');}
   if(a==='difficulty'){this.save.profile.difficulty=Number(b.dataset.index);actions.persist();this.show('expedition');}
  });
  this.root.addEventListener('input',event=>{const t=event.target as HTMLInputElement;if(!t.dataset.setting)return;const key=t.dataset.setting as keyof Settings;this.save.settings={...this.save.settings,[key]:key==='volume'?Number(t.value):t.checked};actions.settings(this.save.settings);const label=this.root.querySelector('#volume-value');if(label)label.textContent=`${Math.round(this.save.settings.volume*100)} %`;});
 }
 menu(){
  const p=this.save.profile,b=p.presets[p.selected],c=CLASSES[b.classId],weapon=WEAPONS[b.startWeapon];
  const guardian=b.classId==='warrior'&&b.masteries.includes('guardian')?p.masteries.guardian:0;
  const stored=this.save.run as {time:number;level:number;floor:number;config:{classId:ClassId}}|null;
  this.view='menu';this.root.className='menu-screen sanctuary-menu';
  const nav=(action:string,title:string,sub:string,img:string)=>`<button class="sanctuary-nav" data-action="${action}">${icon(img)}<span><b>${title}</b><small>${sub}</small></span><span class="nav-chevron" aria-hidden="true">›</span></button>`;
  this.root.innerHTML=`
   <div class="sanctuary-art" aria-hidden="true"></div><div class="sanctuary-vignette" aria-hidden="true"></div><div class="ember-field" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>
   <header class="sanctuary-header"><div class="edition-label"><span class="status-dot"></span> DIE LETZTE ZUFLUCHT <small>V3 · SCHRITT 1</small></div><div class="sanctuary-brand"><h1>STILLALIVE</h1><span>E T A G E N</span></div><div class="header-tools"><button class="wallet-button" data-action="economy" title="Belohnungen und Preise">${icon('gold')}<span>${Math.floor(p.gold).toLocaleString('de-DE')}</span>${icon('soul')}<span>${p.souls}</span></button><button class="settings-corner" data-action="settings" aria-label="Einstellungen">${icon('settings')}</button></div></header>
   <div class="sanctuary-layout">
    <aside class="sanctuary-left"><span class="section-kicker">DEIN VERMÄCHTNIS</span>${nav('shop','Waffenkammer','Neue Spielweisen entdecken','blade')}${nav('passives','Talismane','Passive Kräfte & Schutz','regen')}${nav('builds','Dein Build','Vorlagen und Kartenpool','soulbook')}${nav('permanent','Grundwerte','Bleibende Stärke','armor')}${nav('masteries','Meisterschaften','Macht aus Seelenfragmenten','soul')}<button class="economy-link" data-action="economy">Belohnungen & Preise ansehen</button></aside>
    <section class="survivor-center" aria-label="Dein Charakter"><span class="center-eyebrow">WÄHLE DEINEN ÜBERLEBENDEN</span><div class="hero-stage"><div class="hero-aura"></div><div class="hero-ground"></div><div class="hero-idle" style="background-image:url(assets/${c.texture}.png)" role="img" aria-label="${c.name}"></div></div><div class="hero-caption"><span class="class-mechanic">${c.mechanic}</span><h2>${c.name}</h2><p>${c.description}</p></div><div class="class-switcher" role="group" aria-label="Klasse auswählen">${CLASS_IDS.map(id=>`<button data-action="home-class" data-id="${id}" class="${b.classId===id?'selected':''}" aria-pressed="${b.classId===id}" title="${CLASSES[id].name}"><span class="class-thumb" style="background-image:url(assets/${CLASSES[id].texture}.png)"></span><span>${id==='warrior'?'Krieger':id==='mage'?'Magier':'Jäger'}</span></button>`).join('')}</div><button class="sanctuary-start" data-action="${stored?'continue':'start'}"><span>${stored?'Runde fortsetzen':'Spiel starten'}</span><span aria-hidden="true">→</span></button><p class="start-caption">${stored?`${CLASSES[stored.config.classId].name} · Etage ${stored.floor} · ${formatTime(stored.time)} · Level ${stored.level}`:'Automatische Angriffe · WASD bewegen · Leertaste ausweichen'}</p></section>
    <aside class="sanctuary-right"><span class="section-kicker">DEIN NÄCHSTER LAUF</span><div class="run-preview"><span class="small-label">AKTIVE VORLAGE</span><h3>${escape(b.name)}</h3><div class="starting-weapon">${icon(weapon.icon)}<span><small>STARTWAFFE</small><b>${weapon.name}</b><small>${weapon.damage} ATK · ${weapon.cooldown.toFixed(2)} s</small></span></div><div class="hero-stat-strip"><div><b>${c.hp+p.permanent.health*5+guardian*3}</b><small>LEBEN</small></div><div><b>${c.defense+p.permanent.defense*2+guardian*4}</b><small>DEF</small></div><div><b>${Math.round(c.speed*(1+p.permanent.speed*.01))}</b><small>TEMPO</small></div></div><button data-action="builds" class="quiet-button">Ausrüstung anpassen</button></div><button class="arena-preview" data-action="expedition"><span class="small-label">${DIFFICULTIES[p.difficulty].name.toUpperCase()}</span><b>${DIFFICULTIES[p.difficulty].arena}</b><small>Schwierigkeit ändern <span aria-hidden="true">›</span></small></button><div class="sanctuary-note"><span class="small-label">DEIN FORTSCHRITT BLEIBT</span><p>Gold für dein Arsenal.<br>Eine Truhe nach jeder Etage.</p><span>8 Waffenstufen · 8 passive Plätze</span></div></aside>
   </div><footer class="sanctuary-footer"><div><button class="compact-arena" data-action="expedition">Arena</button><button data-action="characters">Charaktere</button><button data-action="stats">Chronik</button><button data-action="controls">Steuerung</button></div><span><i class="status-dot"></i> Lokal gespeichert · bereit für die nächste Nacht</span></footer>`;
 }
 private dialog(title:string,sub:string,body:string,wide=false){this.root.querySelector('.dialog-layer')?.remove();this.root.insertAdjacentHTML('beforeend',`<div class="dialog-layer"><section class="dialog ${wide?'wide-dialog':''}" role="dialog" aria-modal="true" aria-label="${title}"><button class="close" data-action="close-dialog" aria-label="Schließen">×</button><span class="eyebrow">STILLALIVE V3</span><h2>${title}</h2><p class="dialog-sub">${sub}</p>${body}<button class="secondary full" data-action="close-dialog">Zurück</button></section></div>`);this.root.querySelector<HTMLButtonElement>('.dialog button')?.focus();}
 private wallet(){return `${Math.floor(this.save.profile.gold)} Gold · ${this.save.profile.souls} Seelenfragmente`;}
 show(page:string){this.page=page;const p=this.save.profile,b=p.presets[p.selected];
  if(page==='settings'){const s=this.save.settings;this.dialog('Einstellungen','Eigene synthetische Klänge. Alle Änderungen werden sofort gespeichert.',`<div class="setting"><label for="volume">Lautstärke</label><span id="volume-value">${Math.round(s.volume*100)} %</span><input id="volume" type="range" min="0" max="1" step=".01" value="${s.volume}" data-setting="volume"></div>${(['shake','numbers','particles'] as const).map((key,i)=>`<label class="toggle-row"><span>${['Bildschirmerschütterung','Schadenszahlen','Partikeleffekte'][i]}</span><input type="checkbox" data-setting="${key}" ${s[key]?'checked':''}><span class="toggle"></span></label>`).join('')}`);}
  if(page==='controls')this.dialog('Die Nacht überleben','WASD / Pfeiltasten bewegen · Angriffe automatisch',`<div class="guide"><p><kbd>LEERTASTE</kbd> Ausweichschritt: kurz unverwundbar, Schaden im Startbereich. <kbd>ESC</kbd> / <kbd>P</kbd> Pause. <kbd>1</kbd> <kbd>2</kbd> <kbd>3</kbd> Karte wählen.</p><p>Kristalle bringen XP. Zwischen Kartenwahlen liegen mindestens 20 Sekunden Kampfzeit; überschüssige XP bleiben erhalten. Pro Level: drei Angebote und 1 LP Heilung. Seltene Karten gewähren zusätzlich +1 %, epische +2 % Run-Schaden.</p><p><b>Etagen:</b> Überlebe drei Minuten aktive Kampfzeit. Danach stoppt der Kampf und du wählst einen von drei zufälligen Run-Boni aus der Belohnungstruhe. Starte anschließend die nächste Etage. Waffen, passive Kräfte, Erfahrung und Leben bleiben erhalten.</p><p>Gegner greifen im Nahkampf an. Rote Markierungen kündigen Anstürme und Bossstampfer an. Abstand halten!</p><p>Automatische Boss- und Finsternisregeln sind in Schritt 1 ausgesetzt. Nach jeder Etage steigen Gegner-LP um 15 % und Kontaktschaden um 8 % der Basis.</p><p><b>Pause → Speichern & Hauptmenü</b> sichert die ganze Runde. Freiwilliges Beenden behält verdiente Ressourcen. Automatisch alle 15 Spielsekunden und beim Fensterwechsel gespeichert.</p><p>8 Angriffsslots (Stufe 8), 8 passive Slots (Stufe 8). Nach vollständigem Ausbau: automatische Run-Meisterschaft statt weiterer Kartenpausen.</p></div>`);
  if(page==='characters')this.dialog('Wähle deinen Überlebenden',`${this.wallet()} · Auswahl bestimmt den Build für die nächste neue Runde.`, `<div class="catalog three">${CLASS_IDS.map(id=>{const c=CLASSES[id];return `<article class="catalog-card ${b.classId===id?'selected':''}"><div class="mini-sprite" style="background-image:url(assets/${c.texture}.png)"></div><h3>${c.name}</h3><p>${c.description}</p><p>Basis: LP ${c.hp} · DEF ${c.defense} · Tempo ${c.speed}<br>ATK ×${c.damage} · Krit ${Math.round(c.crit*100)} %</p><button class="secondary full" data-action="class" data-id="${id}">${b.classId===id?'Ausgewählt':'Auswählen'}</button></article>`;}).join('')}</div>`,true);
  if(page==='economy')this.dialog('Belohnungen & Preise',`${this.wallet()} · Regeln für Anfänger; höhere Schwierigkeiten multiplizieren die Beute.`, `<div class="economy-rules">${Object.values(ECONOMY_GUIDE).map(text=>`<p>${text}</p>`).join('')}</div><h3>Grundwerte: Preis je nächster Stufe</h3><div class="price-ladder">${Array.from({length:10},(_,i)=>`<span><b>${i+1}</b>${permanentCost(i)} Gold</span>`).join('')}</div><p class="muted">Schritt 1: Die alten Boss-Belohnungen sind derzeit ausgesetzt; es erscheinen keine zeitgesteuerten Bosse.</p><h3>Historische V2-Bosswerte</h3><div class="economy-rules">${DIFFICULTIES.map((d,i)=>`<p><b>${d.name}</b><span>${goldReward('boss',240,i)} Gold · ${fragmentReward(240,i)} Fragmente</span></p>`).join('')}</div><p class="muted">Käufe gelten für neue Runden. Gold und Fragmente bleiben nach Tod oder freiwilligem Beenden erhalten.</p>`,true);
  if(page==='passives')this.dialog('Passive Talismane',`${this.wallet()} · Bis zu acht passive Fähigkeiten. Im Run erscheint immer eine passive Karte, solange dein Pool eine erlaubt.`, `<div class="catalog">${PASSIVE_IDS.map(id=>{const v=PASSIVES[id],owned=p.passives.includes(id);return `<article class="catalog-card">${icon(v.icon)}<span class="small-label">PASSIV · ${RULES.passiveMax} STUFEN</span><h3>${v.name}</h3><p>${v.description} pro Stufe.</p><button class="secondary full" data-action="buy" data-type="passive" data-id="${id}" ${owned||p.gold<v.cost?'disabled':''}>${owned?'Freigeschaltet':`${v.cost} Gold`}</button></article>`;}).join('')}</div><button class="primary full" data-action="builds">Passiven Kartenpool anpassen</button>`,true);
  if(page==='shop')this.dialog('Das Arsenal',`${this.wallet()} · Freischaltungen werden im Build-Editor gezielt aktiviert.`, `<div class="catalog">${WEAPON_IDS.map(id=>{const w=WEAPONS[id],owned=p.weapons.includes(id);return `<article class="catalog-card">${icon(w.icon)}<span class="small-label">${w.class==='all'?'UNIVERSELL':CLASSES[w.class].name}</span><h3>${w.name}</h3><p>${w.subtitle}</p><p>ATK ${w.damage} · ${w.cooldown} s · RW ${w.range}</p><small>${MILESTONES[w.kind]}</small><button class="secondary full" data-action="buy" data-type="weapon" data-id="${id}" ${owned||p.gold<w.cost?'disabled':''}>${owned?'Freigeschaltet':`${w.cost} Gold`}</button></article>`;}).join('')}${PASSIVE_IDS.map(id=>{const s=PASSIVES[id],owned=p.passives.includes(id);return `<article class="catalog-card">${icon(s.icon)}<span class="small-label">PASSIV</span><h3>${s.name}</h3><p>${s.description}</p><button class="secondary full" data-action="buy" data-type="passive" data-id="${id}" ${owned||p.gold<s.cost?'disabled':''}>${owned?'Freigeschaltet':`${s.cost} Gold`}</button></article>`;}).join('')}</div>`,true);
  if(page==='permanent')this.dialog('Das Vermächtnis',`${this.wallet()} · Maximal 10 Stufen je Wert. Gilt ab der nächsten neuen Runde.`, `<div class="catalog">${(Object.keys(PERMANENT) as PermanentId[]).map(id=>{const s=PERMANENT[id],lv=p.permanent[id];return `<article class="catalog-card"><h3>${s.name} <small>${lv}/10</small></h3><p>${s.description} pro Stufe</p><button class="secondary full" data-action="buy" data-type="permanent" data-id="${id}" ${lv===10||p.gold<permanentCost(lv)?'disabled':''}>${lv===10?'Vollendet':`${permanentCost(lv)} Gold`}</button></article>`;}).join('')}</div><p>DEF reduziert Schaden um DEF / (100 + DEF), höchstens 70 %. Käufe verändern gespeicherte Runden nicht rückwirkend.</p>`,true);
  if(page==='masteries')this.dialog('Klassen-Meisterschaften',`${this.wallet()} · Vorhandene V2-Meisterschaften bleiben nutzbar. Bossfragmente sind in Schritt 1 ausgesetzt.`, `<div class="catalog">${MASTERY_IDS.map(id=>{const m=MASTERIES[id],lv=p.masteries[id];return `<article class="catalog-card"><span class="small-label">${CLASSES[m.class].name}</span><h3>${m.name} <small>${lv}/5</small></h3><p>${m.description}</p><button class="secondary full" data-action="buy" data-type="mastery" data-id="${id}" ${lv===5||p.souls<masteryCost(lv)?'disabled':''}>${lv===5?'Vollendet':`${masteryCost(lv)} Fragmente`}</button></article>`;}).join('')}</div>`,true);
  if(page==='builds')this.dialog('Deine Build-Vorlagen','Ein Startangriff. Der gewählte Pool bestimmt die Angebote im Run. Bis zu 12 Vorlagen.',`<div class="catalog">${p.presets.map((s,i)=>`<article class="catalog-card ${p.selected===i?'selected':''}"><span class="small-label">${CLASSES[s.classId].name}</span><h3>${escape(s.name)}</h3><p>${WEAPONS[s.startWeapon].name}<br>${s.weapons.length} Angriffe · ${s.passives.length} Passives · ${s.masteries.length} Meisterschaften</p><button class="secondary full" data-action="select-preset" data-index="${i}">${p.selected===i?'Ausgewählt':'Auswählen'}</button>${p.selected===i?`<button class="primary full" data-action="edit-preset" data-index="${i}">Bearbeiten</button>`:''}</article>`).join('')}</div>`,true);
  if(page==='expedition')this.dialog('Wähle deine Nacht',`${CLASSES[b.classId].name} · ${escape(b.name)} · Start: ${WEAPONS[b.startWeapon].name}`,`<div class="difficulty-list">${DIFFICULTIES.map((d,i)=>`<button class="difficulty ${p.difficulty===i?'selected':''}" data-action="difficulty" data-index="${i}" ${i>p.unlockedDifficulty?'disabled':''}><b>${d.name}</b><span>${d.arena}</span><small>${i>p.unlockedDifficulty?`V3-Freischaltung folgt in einem späteren Schritt`:`Gegner-LP ×${d.hp} · Schaden ×${d.damage} · Beute ×${d.reward}`}</small></button>`).join('')}</div><button class="primary full" data-action="start">Durchlauf beginnen</button>`);
  if(page==='stats'){const s=this.save.stats;this.dialog('Deine Chronik',`${s.runs} Runden · ${s.floors} V3-Etagen · ${s.kills} Gegner · Rekord ${formatTime(s.bestTime)} / Level ${s.bestLevel}`,`<div class="history">${this.save.history.length?this.save.history.map(h=>`<div><b>${CLASSES[h.className as ClassId]?.name??escape(h.className)}</b><span>${formatTime(h.time)} · ${h.ending==='retired'?'Beendet':'Gefallen'} · ${DIFFICULTIES[h.difficulty].name}</span><small>${h.kills} Gegner · ${h.floors} Etagen · ${h.gold} Gold · ${h.souls} Fragmente</small></div>`).join(''):'Noch keine abgeschlossene Runde.'}</div>`);}
 }
 private editor(){const d=this.draft!,p=this.save.profile;this.dialog('Build bearbeiten','Nur die Startwaffe ist sofort aktiv. Bis zu 8 Angriffe und 8 Passives werden im Run erworben.',`<label class="editor-label">Name<input id="build-name" maxlength="36" value="${escape(d.name)}"></label><label class="editor-label">Startwaffe<select id="build-start">${p.weapons.filter(id=>WEAPONS[id].class===d.classId||WEAPONS[id].class==='all').map(id=>`<option value="${id}" ${d.startWeapon===id?'selected':''}>${WEAPONS[id].name}</option>`).join('')}</select></label><h3>Angriffspool</h3><div class="check-grid">${p.weapons.filter(id=>WEAPONS[id].class===d.classId||WEAPONS[id].class==='all').map(id=>`<label><input type="checkbox" data-weapon="${id}" ${d.weapons.includes(id)?'checked':''}>${WEAPONS[id].name}</label>`).join('')}</div><h3>Passiver Pool</h3><div class="check-grid">${p.passives.map(id=>`<label><input type="checkbox" data-passive="${id}" ${d.passives.includes(id)?'checked':''}>${PASSIVES[id].name}</label>`).join('')}</div><h3>Meisterschaften · maximal 3</h3><div class="check-grid">${MASTERY_IDS.filter(id=>MASTERIES[id].class===d.classId).map(id=>`<label><input type="checkbox" data-mastery="${id}" ${d.masteries.includes(id)?'checked':''} ${p.masteries[id]===0?'disabled':''}>${MASTERIES[id].name} ${p.masteries[id]}/5</label>`).join('')}</div><button class="primary full" data-action="save-preset">Vorlage speichern</button><button class="secondary full" data-action="copy-preset" ${p.presets.length>=12?'disabled':''}>Als neue Vorlage speichern</button>`,true);}
 private saveDraft(){const d=this.draft!;d.name=(this.root.querySelector('#build-name') as HTMLInputElement).value;d.startWeapon=(this.root.querySelector('#build-start') as HTMLSelectElement).value as WeaponId;d.weapons=[...this.root.querySelectorAll<HTMLInputElement>('[data-weapon]:checked')].map(t=>t.dataset.weapon as WeaponId);d.passives=[...this.root.querySelectorAll<HTMLInputElement>('[data-passive]:checked')].map(t=>t.dataset.passive as PassiveId);d.masteries=[...this.root.querySelectorAll<HTMLInputElement>('[data-mastery]:checked')].map(t=>t.dataset.mastery as MasteryId);}
 startHud(){this.view='playing';this.root.className='game-ui';this.root.innerHTML=`<div class="hud-top"><div class="vitals"><div class="vitals-label"><span id="class-name"></span><strong id="hp-text"></strong></div><div class="hp-track"><div id="hp-bar"></div></div><div class="level-row"><span id="level-text"></span><div class="xp-track"><div id="xp-bar"></div></div><span id="xp-text"></span></div><small id="live-stats"></small></div><div class="run-clock"><span id="phase-name"></span><strong id="timer">00:00</strong><span id="phase-timer"></span><small id="resource-text"></small></div><div class="run-count"><span>GEFALLENE</span><strong id="kills">0</strong><button data-action="pause">Pause <span>ESC</span></button></div></div><div id="boss-hud" class="boss-hud" hidden><span id="boss-name"></span><div><i id="boss-bar"></i></div></div><div class="hud-bottom"><div class="arsenal"><span class="small-label">ANGRIFFE <small id="mechanic"></small></span><div id="weapons" class="weapon-slots"></div><span class="small-label">PASSIVES</span><div id="passives" class="weapon-slots"></div></div><div class="dash-panel"><div class="dash-icon">${icon('speed')}</div><div><span>AUSWEICHSCHRITT</span><div class="dash-track"><i id="dash-bar"></i></div><small id="dash-text"></small></div></div></div><div id="toast" class="toast" role="status"></div><div id="overlay"></div>`;this.lastHud=0;}
 update(e:Engine,force=false){if(!document.getElementById('timer'))return;const now=performance.now();if(!force&&now-this.lastHud<120)return;this.lastHud=now;const set=(id:string,t:string)=>{const n=document.getElementById(id);if(n&&n.textContent!==t)n.textContent=t;};const width=(id:string,v:number)=>{document.getElementById(id)!.style.width=`${Math.max(0,Math.min(100,v))}%`;};set('class-name',CLASSES[e.config.classId].name);set('hp-text',`${Math.ceil(e.player.hp)} / ${e.player.maxHp}`);width('hp-bar',e.player.hp/e.player.maxHp*100);set('level-text',`LV. ${e.level}`);set('xp-text',e.xp>=xpForLevel(e.level)&&e.time<e.nextChoiceAt?`XP gesichert · Wahl in ${Math.ceil(e.nextChoiceAt-e.time)} s`:`${Math.floor(e.xp)}/${xpForLevel(e.level)}`);width('xp-bar',e.xp/xpForLevel(e.level)*100);set('timer',formatTime(Math.ceil(e.floorRemaining)));set('kills',String(e.kills));set('phase-name',`ETAGE ${e.floor}`);set('phase-timer',`${e.floorDuration<180?'SCHNELLTEST · ':''}${DIFFICULTIES[e.config.difficulty].arena} · Gesamt ${formatTime(e.time)}`);set('resource-text',`${Math.floor(e.gold)} Gold · ${e.completedFloors} Etagen geschafft`);set('live-stats',`ATK ×${e.damageMultiplier.toFixed(2)} · DEF ${e.defense} (${Math.round(reduction(e.defense)*100)} %) · Krit ${Math.round(e.criticalChance*100)} %`);set('mechanic',e.config.classId==='warrior'?`Wut ${Math.round(e.rage*100)} %`:e.config.classId==='mage'?`Überladung ${e.casts%6}/6`:'Markierung: 3 Treffer');width('dash-bar',(1-e.player.dashCooldown/e.dashCooldown)*100);set('dash-text',e.player.dashCooldown>0?`${e.player.dashCooldown.toFixed(1)} s`:'LEERTASTE · BEREIT');
  for(const [host,ids,levels,max] of [['weapons',WEAPON_IDS,e.build.weapons,RULES.weaponMax],['passives',PASSIVE_IDS,e.build.passives,8]] as const){const n=document.getElementById(host)!,key=JSON.stringify(levels);if(n.dataset.build===key)continue;n.dataset.build=key;const equipped=ids.filter(id=>(levels as any)[id]>0);n.innerHTML=equipped.map(id=>`<div class="weapon-slot equipped" title="${id in WEAPONS?WEAPONS[id as WeaponId].name:PASSIVES[id as PassiveId].name} · ${(levels as any)[id]}/${max}">${itemIcon(id)}<span>${(levels as any)[id]}</span>${host==='weapons'?`<i class="weapon-cooldown" id="cd-${id}"></i>`:''}</div>`).join('')+Array.from({length:Math.max(0,8-equipped.length)},()=>'<div class="weapon-slot empty"></div>').join('');}
  for(const id of WEAPON_IDS){const bar=document.getElementById(`cd-${id}`);if(bar)bar.style.width=`${Math.max(0,Math.min(1,1-e.cooldowns[id]/(weaponStats(id,e.build.weapons[id]).cooldown/e.attackSpeed)))*100}%`;}
  const boss=e.boss;document.getElementById('boss-hud')!.hidden=!boss;if(boss){set('boss-name',`${ENEMIES[boss.kind].name} · ${Math.ceil(boss.hp)} LP`);width('boss-bar',boss.hp/boss.maxHp*100);}this.root.classList.toggle('eclipse',e.eclipse);
 }
 overlay(e:Engine){const host=document.getElementById('overlay');if(!host)return;this.view=e.status;if(e.status==='playing'){host.innerHTML='';return;}
  if(e.status==='paused')host.innerHTML=`<div class="overlay-backdrop"><section class="pause-card"><span class="eyebrow">EIN MOMENT DER STILLE</span><h2>Die Nacht wartet.</h2><p>Etage ${e.floor} · ${formatTime(Math.ceil(e.floorRemaining))} verbleibend · ${Math.floor(e.gold)} Gold</p><button class="primary full" data-action="resume">Weiterkämpfen</button><button class="secondary full" data-action="settings">Einstellungen</button><button class="secondary full" data-action="suspend">Speichern & Hauptmenü</button><button class="text-button full" data-action="retire">Runde freiwillig beenden</button><small>Verdiente Ressourcen bleiben bei beiden Optionen erhalten.</small></section></div>`;
  if(e.status==='upgrade')host.innerHTML=`<div class="overlay-backdrop upgrade-backdrop"><section class="upgrade-panel"><span class="eyebrow">LEVEL ${e.level} · +1 LP</span><h2>Die Schatten schenken Macht.</h2><p>Waffen und Talismane aus deinem Kartenpool.</p><div class="upgrade-cards">${e.offers.map((o,i)=>{const weapon=o.id in WEAPONS,info=weapon?WEAPONS[o.id as WeaponId]:PASSIVES[o.id as PassiveId],lv=weapon?e.build.weapons[o.id as WeaponId]:e.build.passives[o.id as PassiveId];return `<button class="upgrade-card ${o.rarity}" data-action="upgrade" data-index="${i}" style="--accent:${info.color}"><span class="rarity">${o.rarity==='epic'?'EPISCH':o.rarity==='rare'?'SELTEN':'GEWÖHNLICH'}<kbd>${i+1}</kbd></span><div class="upgrade-icon">${itemIcon(o.id)}</div><span class="card-type">${o.recovery?'RUN-MEISTERSCHAFT':weapon?'WAFFENVERBESSERUNG':'PASSIVER TALISMAN'}</span><h3>${o.recovery?'Vermächtnis':info.name}</h3><span class="card-level">${o.recovery?'WIEDERHOLBAR':`STUFE ${lv+1}/${weapon?RULES.weaponMax:RULES.passiveMax}`}</span><p>${upgradeDescription(o,e.build)}</p><div class="card-footer">${o.bonus?`Zusätzlich +${o.bonus} % Run-Schaden`:'Wählen'} →</div></button>`;}).join('')}</div></section></div>`;
  if(e.status==='floorReward')host.innerHTML=`<div class="overlay-backdrop upgrade-backdrop"><section class="upgrade-panel"><span class="eyebrow">ETAGE ${e.floor} ABGESCHLOSSEN</span><h2>Deine Belohnungstruhe</h2><p>Wähle genau einen Bonus. Er gilt für diese Runde und bleibt auf den nächsten Etagen erhalten.</p><div class="upgrade-cards">${e.rewardOffers.map((o,i)=>{const w=o.id in WEAPONS,info=w?WEAPONS[o.id as WeaponId]:PASSIVES[o.id as PassiveId];return `<button class="upgrade-card ${o.rarity}" data-action="reward" data-index="${i}" style="--accent:${info.color}"><span class="rarity">${o.rarity==='epic'?'EPISCH':o.rarity==='rare'?'SELTEN':'GEWÖHNLICH'}<kbd>${i+1}</kbd></span><div class="upgrade-icon">${itemIcon(o.id)}</div><span class="card-type">TEMPORÄRER RUN-BONUS</span><h3>${o.recovery?'Run-Meisterschaft':info.name}</h3><p>${upgradeDescription(o,e.build)}</p><div class="card-footer">${o.bonus?`Zusätzlich +${o.bonus} % Run-Schaden`:"Aus der Truhe wählen"} →</div></button>`;}).join('')}</div><button class="secondary" data-action="suspend">Speichern & Hauptmenü</button></section></div>`;
  if(e.status==='floorReady')host.innerHTML=`<div class="overlay-backdrop"><section class="pause-card"><span class="eyebrow">ETAGE ${e.floor} ABGESCHLOSSEN</span><h2>Bereit für Etage ${e.floor+1}?</h2><p>Gewählt: <b>${e.chosenReward?.recovery?'Run-Meisterschaft':e.chosenReward?.id&&e.chosenReward.id in WEAPONS?WEAPONS[e.chosenReward.id as WeaponId].name:e.chosenReward?PASSIVES[e.chosenReward.id as PassiveId].name:''}</b></p><p>Dein Build und ${Math.ceil(e.player.hp)} / ${e.player.maxHp} LP bleiben erhalten. Gegner werden etwas stärker.</p><button class="primary full" data-action="nextFloor">Etage ${e.floor+1} starten</button><button class="secondary full" data-action="suspend">Speichern & Hauptmenü</button><button class="text-button full" data-action="retire">Runde freiwillig beenden</button></section></div>`;
  if(e.status==='dead'||e.status==='retired')host.innerHTML=`<div class="overlay-backdrop"><section class="result-card"><img class="result-emblem" src="assets/icon.png" alt=""><span class="eyebrow">DEIN VERMÄCHTNIS BLEIBT</span><h2>${e.status==='dead'?'Im Schatten gefallen.':'Die Nacht überlebt.'}</h2><p>${Math.floor(e.gold)} Gold · ${e.souls} Fragmente behalten</p><div class="result-stats"><div><strong>${formatTime(e.time)}</strong><span>Überlebt</span></div><div><strong>${e.kills}</strong><span>Gegner</span></div><div><strong>${e.level}</strong><span>Level</span></div></div><p>${e.completedFloors} Etagen abgeschlossen</p><div class="result-weapons">${WEAPON_IDS.filter(id=>e.build.weapons[id]).map(id=>`<div>${itemIcon(id)}<span>${WEAPONS[id].name}<small>STUFE ${e.build.weapons[id]}</small></span></div>`).join('')}</div><button class="primary full" data-action="start">Neue Runde mit diesem Menü-Build</button><button class="text-button full" data-action="menu">Zum Hauptmenü</button></section></div>`;host.querySelector<HTMLButtonElement>('button')?.focus();
 }
 toast(message:string){let n=document.getElementById('toast');if(!n){n=document.createElement('div');n.id='toast';n.className='toast';n.setAttribute('role','status');this.root.append(n);}clearTimeout(this.toastTimeout);n.textContent=message;n.classList.add('visible');this.toastTimeout=setTimeout(()=>n?.classList.remove('visible'),4000);}
}
