import {renderRunResult} from './ui/run-result';
import {eclipseSeal} from './ui/design';
import {menuTexture,menuSpriteClass} from './player-animation';
import {RULES,WEAPONS,WEAPON_IDS,PASSIVES,PASSIVE_IDS,CLASSES,DIFFICULTIES,ENEMIES,xpForLevel,reduction,weaponStats,type WeaponId,type PassiveId,type ClassId} from './core/config';
import {PERMANENT,MASTERIES,MASTERY_IDS,permanentCost,normalizePreset,defaultPreset,type PermanentId,type MasteryId,type Preset,type Profile} from './core/meta';

import type {Engine} from './core/engine';
import {upgradeDescription} from './core/upgrades';
import type {Save,Settings} from './core/storage';
import {menuProgress,worldRecord} from './menu-progress';
import {CHARACTERS,characterById,selectCharacter,type CharacterId,type CharacterEntry} from './characters';
export const formatTime=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(id:string)=>`<img class="item-icon" src="assets/icon-${id}.png" alt="" draggable="false">`;
const itemIcon=(id:WeaponId|PassiveId)=>icon(id in WEAPONS?WEAPONS[id as WeaponId].icon:PASSIVES[id as PassiveId].icon);
const number=(n:number,digits=0)=>n.toLocaleString('de-DE',{maximumFractionDigits:digits,minimumFractionDigits:digits});
/** New-run values, without temporary passives or conditional combat bonuses. */
export function homeStats(p:Profile){
 const b=normalizePreset(p.presets[p.selected]??{},p),c=CLASSES[b.classId],v=p.permanent;
 const guardian=b.masteries.includes('guardian')?p.masteries.guardian:0;
 return {health:c.hp+v.health*5+guardian*3,attack:c.damage*(1+v.attack*.02),defense:c.defense+v.defense*2+guardian*4,speed:c.speed*(1+v.speed*.01),crit:Math.min(.75,c.crit+v.crit*.005),critDamage:1.7+v.critDamage*.03,luck:1+v.luck*.01,guardian};
}
export interface Actions {reward:(i:number)=>void;nextFloor:()=>void;start:()=>void;continue:()=>void;resume:()=>void;pause:()=>void;menu:()=>void;suspend:()=>void;retire:()=>void;upgrade:(i:number)=>void;settings:(s:Settings)=>void;persist:()=>void;buy:(type:string,id:string)=>boolean}
export class UI {
 root=document.querySelector<HTMLElement>('#ui')!;view='menu';private lastHud=0;private toastTimeout?:ReturnType<typeof setTimeout>;private page='';private draft?:Preset;
 constructor(public save:Save,private actions:Actions){
  this.root.addEventListener('click',event=>{const b=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action!;
   if(['start','continue','resume','pause','menu','suspend','retire','nextFloor'].includes(a))(actions as any)[a]();
   if(a==='reward')actions.reward(Number(b.dataset.index));if(a==='upgrade')actions.upgrade(Number(b.dataset.index));if(a==='close-dialog')this.closeDialog();
   if(['settings','controls','stats','characters','legacy','codex','permanent','builds','expedition'].includes(a))this.show(a);
   if(a==='buy'){const ok=actions.buy(b.dataset.type!,b.dataset.id!);if(this.view==='menu')this.menu();this.show(this.page);if(!ok)this.toast('Nicht genügend Ressourcen.');}
   if(a==='preview-character'){const c=characterById(b.dataset.id!);if(c&&c.kind!=='future'){this.characterDialog(c.id);this.root.querySelector<HTMLButtonElement>(`[data-character-id="${c.id}"]`)?.focus();if(matchMedia('(max-width:760px)').matches)this.root.querySelector('.character-preview')?.scrollIntoView({block:'start'});}}
   if(a==='choose-character'){
    const result=selectCharacter(this.save.profile,b.dataset.id!);
    if(result==='selected'){actions.persist();this.closeDialog();}
    else this.toast(result==='preset-limit'?'Dein Vorlagenlimit ist erreicht. Für diese Klasse fehlt noch eine Vorlage; vorhandene Vorlagen bleiben erhalten.':'Dieser Charakter ist noch nicht spielbar.');
   }
   if(a==='select-preset'){this.save.profile.selected=Number(b.dataset.index);actions.persist();this.show('builds');}
   if(a==='edit-preset'){this.draft=structuredClone(this.save.profile.presets[Number(b.dataset.index)]);this.editor();}
   if(a==='save-preset'){this.saveDraft();this.save.profile.presets[this.save.profile.selected]=normalizePreset(this.draft!,this.save.profile);actions.persist();this.show('builds');}
   if(a==='copy-preset'&&this.save.profile.presets.length<12){this.saveDraft();this.save.profile.presets.push(normalizePreset(this.draft!,this.save.profile));this.save.profile.selected=this.save.profile.presets.length-1;actions.persist();this.show('builds');}
   if(a==='difficulty'){this.save.profile.difficulty=Number(b.dataset.index);actions.persist();this.menu();this.show('expedition');}
  });
  this.root.addEventListener('input',event=>{const t=event.target as HTMLInputElement;if(!t.dataset.setting)return;const key=t.dataset.setting as keyof Settings;this.save.settings={...this.save.settings,[key]:key==='volume'?Number(t.value):t.checked};actions.settings(this.save.settings);const label=this.root.querySelector('#volume-value');if(label)label.textContent=`${Math.round(this.save.settings.volume*100)} %`;if(key==='volume')t.style.setProperty('--fill',`${Math.round(Number(t.value)*100)}%`);});
 }
 menu(){
  const p=this.save.profile,b=p.presets[p.selected],c=CLASSES[b.classId],stats=homeStats(p),progress=menuProgress(this.save);
  const world=DIFFICULTIES[p.difficulty],record=worldRecord(this.save,p.difficulty);
  const stored=this.save.run as {time:number;level:number;config:{classId:ClassId}}|null;
  const nav=(action:string,image:string,title:string,sub:string)=>`<button class="sanctuary-nav" data-action="${action}" aria-label="${title}" aria-haspopup="dialog">${icon(image)}<span><b>${title}</b><small>${sub}</small></span><span class="nav-chevron" aria-hidden="true">›</span></button>`;
  const rows=[['heroes','armor','Helden',progress.heroes,'Spielbare Charaktere / alle vorgesehenen Charakterplätze'],['upgrades','power','Upgrades',progress.upgrades,'Freigeschaltete Waffen und Passives; jede registrierte ID zählt einmal, Stufen zählen nicht zusätzlich'],['worlds','reach','Welten (max)',progress.worlds,'Noch keine erfolgreich geschaffte Endless-Welt gespeichert. Die 30-Minuten-Freischaltung folgt später.']] as const;
  this.view='menu';this.root.className='menu-screen sanctuary-menu menu-v4';
  this.root.innerHTML=`
   <div class="sanctuary-art" aria-hidden="true"></div><div class="sanctuary-vignette" aria-hidden="true"></div><div class="sanctuary-mist" aria-hidden="true"></div><div class="ember-field" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>
   <header class="sanctuary-header"><div class="sanctuary-brand"><h1>STILLALIVE</h1><span>ENDLESS</span><p>DIE LETZTE ZUFLUCHT</p></div><div class="header-tools"><div class="wallet-button" role="group" aria-label="Gold und Seelenfragmente">${icon('gold')}<span>${number(Math.floor(p.gold))}</span>${icon('soul')}<span>${number(p.souls)}</span></div><button class="settings-corner" data-action="settings" aria-label="Einstellungen">${icon('settings')}</button></div></header>
   <div class="sanctuary-layout">
    <aside class="sanctuary-left"><nav aria-label="Hauptmenü">${nav('characters','armor','Charaktere','Helden auswählen')}${nav('legacy','power','Vermächtnis','Permanente Verbesserungen')}${nav('codex','soulbook','Kodex','Waffen, Fähigkeiten und Entdeckungen')}</nav><section class="home-progress" aria-label="Dein Fortschritt"><h2>DEIN FORTSCHRITT</h2>${rows.map(([key,image,label,v,tip])=>`<div class="progress-row" data-progress="${key}" title="${tip}">${icon(image)}<span>${label}</span><div class="progress-track" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${v.total}" aria-valuenow="${v.current}"><i style="width:${v.total?v.current/v.total*100:0}%"></i></div><b>${v.current} / ${v.total}</b></div>`).join('')}</section></aside>
    <section class="survivor-center" aria-label="Dein Charakter"><div class="hero-stage"><div class="hero-aura"></div><div class="hero-ground"></div><div class="hero-idle${menuSpriteClass(b.classId)}" style="background-image:url(assets/${menuTexture(b.classId)}.png)" role="img" aria-label="${c.name}"></div></div><div class="hero-caption"><h2>${c.name}</h2><p>${c.description}</p></div><div class="home-stat-bar" aria-label="Grundwerte für die nächste Runde"><div class="home-stat" data-stat="health">${icon('vitality')}<span><b>${number(stats.health)}</b><small>HP</small></span></div><div class="home-stat" data-stat="attack" title="Grundschaden-Multiplikator ohne temporäre Kampfboni">${icon('blade')}<span><b>×${number(stats.attack,2)}</b><small>ATK</small></span></div><div class="home-stat" data-stat="defense">${icon('armor')}<span><b>${number(stats.defense)}</b><small>DEF</small></span></div></div><button class="sanctuary-start" data-action="${stored?'continue':'start'}" aria-label="${stored?'Runde fortsetzen':'Spiel starten'}"><span>${stored?'RUNDE FORTSETZEN':'SPIEL STARTEN'}</span><span aria-hidden="true">→</span></button><p class="start-caption">${stored?`${CLASSES[stored.config.classId].name} · ${formatTime(stored.time)} · Level ${stored.level}`:'WASD bewegen · Angriffe automatisch · Leertaste ausweichen'}</p></section>
    <aside class="sanctuary-right world-panel" aria-label="Aktuelle Welt"><div class="world-panel-heading"><span class="section-kicker">DEINE NÄCHSTE WELT</span><button data-action="expedition" aria-label="Welten ansehen">›</button></div><div class="world-art world-art-${p.difficulty}" role="img" aria-label="Atmosphärische Illustration der Zuflucht"></div><div class="world-name"><h2>${world.arena}</h2><span>${world.name}</span></div><p class="world-number">Welt ${p.difficulty+1} / ${DIFFICULTIES.length}</p><button class="world-switch" data-action="expedition">WELT WECHSELN</button><div class="world-record"><span class="section-kicker">DEIN REKORD</span><div title="Höchstwerte aus den letzten ${this.save.history.length} gespeicherten Runden dieser Chronik"><span>${icon('haste')}<b data-world-record="time">${record?formatTime(record.time):'—:—'}</b></span><span>${icon('ferocity')}<b data-world-record="kills">${record?number(record.kills):'—'}</b><small>KILLS</small></span></div></div><div class="world-goal"><span class="section-kicker">NÄCHSTES FREISCHALTZIEL</span><p>${icon('gold')}<span>${p.unlockedDifficulty<DIFFICULTIES.length-1?'30 Minuten überleben':'Alle vorhandenen Welten zugänglich'}<small>${p.unlockedDifficulty<DIFFICULTIES.length-1?'Endless-Freischaltung in Vorbereitung':'Aus deinem bestehenden Spielstand'}</small></span></p></div></aside>
   </div><footer class="sanctuary-footer"><div><button data-action="stats">${icon('soulbook')}Chronik</button><button data-action="controls">${icon('settings')}Steuerung</button></div><span><i class="status-dot"></i> Fortschritt wird lokal gespeichert</span></footer>`;
 }
 closeDialog(){
  if(!this.root.querySelector('.dialog-layer'))return;
  if(this.view==='menu'){const page=this.page==='permanent'?'legacy':this.page;this.menu();this.root.querySelector<HTMLButtonElement>(`[data-action="${page}"]`)?.focus();}
  else this.root.querySelector('.dialog-layer')?.remove();
 }
 private characterDialog(previewId:CharacterId){
  const p=this.save.profile,active=p.presets[p.selected],entry=characterById(previewId);
  if(!entry||entry.kind==='future')return;
  const lock=`<svg class="character-lock" viewBox="0 0 32 32" aria-hidden="true"><path d="M10 14V8h12v6M8 14h16v13H8zM16 19v4"/></svg>`;
  const art=(c:CharacterEntry)=>c.kind==='playable'?`<span class="character-card-sprite${menuSpriteClass(c.id)}" style="background-image:url(assets/${menuTexture(c.id)}.png)" aria-hidden="true"></span>`:lock;
  const cards=CHARACTERS.map(c=>`<button class="character-card ${c.kind==='future'?'future-character':''} ${c.id===entry.id?'previewed':''} ${c.id===active.classId?'equipped-character':''}" data-action="preview-character" data-id="${c.id}" data-character-id="${c.id}" ${c.kind==='future'?'disabled':''} aria-pressed="${c.id===entry.id}" aria-label="${c.name}${c.kind==='future'?' · Bald verfügbar':' ansehen'}"><span class="character-card-art">${art(c)}</span><b>${c.name}</b><small>${c.kind==='future'?'ZUKÜNFTIGER CHARAKTER':c.role}</small><span class="character-availability">${c.kind==='future'?'Bald verfügbar':c.id===active.classId?'Ausgewählt · Kostenlos':'Verfügbar · Kostenlos'}</span></button>`).join('');
  let preview:string;
  if(entry.kind==='playable'){
   const c=CLASSES[entry.id],preset=active.classId===entry.id?active:p.presets.find(b=>b.classId===entry.id)??defaultPreset(entry.id);
   const stats=homeStats({...p,presets:[preset],selected:0}),w=WEAPONS[preset.startWeapon];
   preview=`<span class="small-label">KOSTENLOSER STARTCHARAKTER</span><div class="character-preview-stage"><div class="character-preview-sprite${menuSpriteClass(entry.id as ClassId)}" style="background-image:url(assets/${menuTexture(entry.id as ClassId)}.png)" role="img" aria-label="${c.name}"></div></div><h3>${c.name}</h3><p class="character-role">${entry.role}</p><div class="character-weapon">${icon(w.icon)}<div><span class="small-label">STARTWAFFE DEINER VORLAGE</span><b>${w.name}</b><small>${w.damage} ATK · ${number(w.cooldown,2)} s</small></div></div><dl class="character-properties"><div><dt>Leben</dt><dd>${number(stats.health)} LP</dd></div><div><dt>Angriff</dt><dd>×${number(stats.attack,2)}</dd></div><div><dt>Verteidigung</dt><dd>${number(stats.defense)} DEF</dd></div><div><dt>Tempo</dt><dd>${number(stats.speed,1)}</dd></div><div><dt>Krit-Grundchance</dt><dd>${number(stats.crit*100,1)} %</dd></div></dl><p class="character-values-note">Startwerte inklusive permanenter Verbesserungen und ausgerüsteter Meisterschaften.</p><div class="character-ability"><span class="small-label">SPEZIALFÄHIGKEIT · ${c.mechanic}</span><p>${c.description}</p></div><button class="primary full character-select" data-action="choose-character" data-id="${entry.id}" ${entry.id===active.classId?'disabled':''}>${entry.id===active.classId?'Ausgewählt':'Auswählen'}</button>`;
  }else{return;}
  this.dialog('Charaktere',`Wähle deinen Überlebenden. Drei kostenlose Starter sind sofort spielbar.`,`<div class="character-browser"><section class="character-roster" aria-label="Charakterkarten"><div class="character-roster-heading"><span class="section-kicker">DEINE ÜBERLEBENDEN</span><span>3 Starter · 10 Zukunftsplätze</span></div><div class="character-grid">${cards}</div></section><aside class="character-preview" data-preview-character="${entry.id}" aria-label="Charaktervorschau">${preview}</aside></div><p class="character-dialog-note">Deine Auswahl wird gespeichert und gilt für die nächste neue Runde. Eine gespeicherte Runde behält ihren Charakter und Build. Zukünftige Plätze haben keine Preise oder Kaufmöglichkeiten.</p>`,true);
  this.root.querySelector('.dialog')?.classList.add('character-dialog');
 }
 private permanentDialog(){
  const p=this.save.profile,b=p.presets[p.selected],c=CLASSES[b.classId],stats=homeStats(p);
  const labels:Record<PermanentId,string>={health:'Leben',attack:'Angriff',defense:'Verteidigung',speed:'Bewegungstempo',crit:'Kritische Treffer',critDamage:'Kritischer Schaden',luck:'Glück'};
  const values=(v:ReturnType<typeof homeStats>):Record<PermanentId,string>=>({health:`${number(v.health)} LP`,attack:`×${number(v.attack,2)}`,defense:`${number(v.defense)} DEF`,speed:`${number(v.speed,1)}`,crit:`${number(v.crit*100,1)} %`,critDamage:`×${number(v.critDamage,2)}`,luck:`×${number(v.luck,2)} Gold`});
  const current=values(stats),base=values(homeStats({...p,permanent:{attack:0,defense:0,health:0,speed:0,crit:0,critDamage:0,luck:0}}));
  const icons:Record<PermanentId,string>={health:'vitality',attack:'blade',defense:'armor',speed:'speed',crit:'crit',critDamage:'ferocity',luck:'fortune'};
  const effects:Record<PermanentId,string>={health:'Maximale Lebenspunkte zu Beginn einer neuen Runde.',attack:'Multipliziert den Waffenschaden. Wut und weitere Kampfboni kommen im Run hinzu.',defense:`Aktuell ${number(reduction(stats.defense)*100,1)} % weniger erlittener Schaden. Obergrenze: 70 %.`,speed:'Bewegungsgeschwindigkeit in Weltpixeln pro Sekunde.',crit:'Grundchance auf einen kritischen Treffer; waffenspezifische Boni kommen hinzu.',critDamage:'Schadensmultiplikator bei einem kritischen Treffer.',luck:`+${number(p.permanent.luck,0)} % Gold und +${number(p.permanent.luck,0)} Prozentpunkte im Seltenheitswurf. Run-Boni kommen hinzu.`};
  this.dialog('Vermächtnis',`${c.name} · ${this.wallet()} · Permanente Stärke für die nächste neue Runde.`, `<div class="permanent-summary"><span>${icon('vitality')}<b>${current.health}</b></span><span>${icon('blade')}<b>${current.attack} Angriff</b></span><span>${icon('armor')}<b>${current.defense}</b></span></div><div class="permanent-grid">${(['health','attack','defense','speed','crit','critDamage','luck'] as PermanentId[]).map(id=>{
   const lv=p.permanent[id],s=PERMANENT[id],next=values(homeStats({...p,permanent:{...p.permanent,[id]:Math.min(10,lv+1)}}))[id];
   return `<article class="permanent-card" data-permanent="${id}"><header>${icon(icons[id])}<div><h3>${labels[id]}</h3><small>VERBESSERUNG ${lv} / 10</small></div><strong>${current[id]}</strong></header><div class="rank-track" aria-hidden="true">${Array.from({length:10},(_,i)=>`<i class="${i<lv?'filled':''}"></i>`).join('')}</div><p>${effects[id]}</p><dl><div><dt>Ohne permanente Stufen</dt><dd>${base[id]}</dd></div><div><dt>Bonus pro Stufe</dt><dd>${s.description}</dd></div>${lv<10?`<div><dt>Nächste Stufe</dt><dd>${next}</dd></div>`:''}</dl><button class="secondary full" data-action="buy" data-type="permanent" data-id="${id}" ${lv>=10||p.gold<permanentCost(lv)?'disabled':''}>${lv>=10?'Vollständig verbessert':`Verbessern · ${permanentCost(lv)} Gold`}</button></article>`;
  }).join('')}</div><p class="permanent-explanation">${stats.guardian?`Aktive Wächter-Meisterschaft: +${stats.guardian*3} LP und +${stats.guardian*4} DEF sind enthalten. `:''}Klassenwerte und aktiv ausgerüstete Meisterschaften sind berücksichtigt. Temporäre Run-Upgrades und situationsabhängige Boni sind hier nicht enthalten. DEF reduziert Schaden um DEF / (100 + DEF). Käufe verändern eine gespeicherte Runde nicht rückwirkend.</p>`,true);
 }
 private dialog(title:string,sub:string,body:string,wide=false){this.root.querySelector('.dialog-layer')?.remove();this.root.insertAdjacentHTML('beforeend',`<div class="dialog-layer"><section class="dialog ${wide?'wide-dialog':''}" role="dialog" aria-modal="true" aria-label="${title}"><button class="close" data-action="close-dialog" aria-label="Schließen">×</button><span class="eyebrow">STILLALIVE · ENDLESS</span><h2>${title}</h2><span class="dialog-rule" aria-hidden="true"></span><p class="dialog-sub">${sub}</p>${body}<button class="secondary full" data-action="close-dialog">Zurück</button></section></div>`);this.root.querySelector<HTMLButtonElement>('.dialog button')?.focus();}
 private wallet(){return `${Math.floor(this.save.profile.gold)} Gold · ${this.save.profile.souls} Seelenfragmente`;}
 show(page:string){this.page=page;const p=this.save.profile,b=p.presets[p.selected];
  if(page==='settings'){const s=this.save.settings;this.dialog('Einstellungen','Eigene synthetische Klänge. Alle Änderungen werden sofort gespeichert.',`<div class="setting"><label for="volume">Lautstärke</label><span id="volume-value">${Math.round(s.volume*100)} %</span><input id="volume" type="range" min="0" max="1" step=".01" value="${s.volume}" data-setting="volume" style="--fill:${Math.round(s.volume*100)}%"></div>${(['shake','numbers','particles'] as const).map((key,i)=>`<label class="toggle-row"><span>${['Bildschirmerschütterung','Schadenszahlen','Partikeleffekte'][i]}</span><input type="checkbox" data-setting="${key}" ${s[key]?'checked':''}><span class="toggle"></span></label>`).join('')}`);}
  if(page==='controls')this.dialog('Die Nacht überleben','WASD / Pfeiltasten bewegen · Angriffe automatisch',`<div class="guide"><p><kbd>LEERTASTE</kbd> Ausweichschritt: kurz unverwundbar, Schaden im Startbereich. <kbd>ESC</kbd> / <kbd>P</kbd> Pause. <kbd>1</kbd> <kbd>2</kbd> <kbd>3</kbd> Karte wählen.</p><p>Kristalle bringen XP. Zwischen Kartenwahlen liegen mindestens 20 Sekunden Kampfzeit; überschüssige XP bleiben erhalten. Pro Level: drei Angebote und 1 LP Heilung. Seltene Karten gewähren zusätzlich +1 %, epische +2 % Run-Schaden.</p><p><b>Etagen:</b> Überlebe drei Minuten aktive Kampfzeit. Danach stoppt der Kampf und du wählst einen von drei zufälligen Run-Boni aus der Belohnungstruhe. Starte anschließend die nächste Etage. Waffen, passive Kräfte, Erfahrung und Leben bleiben erhalten.</p><p>Gegner greifen im Nahkampf an. Rote Markierungen kündigen Anstürme und Bossstampfer an. Abstand halten!</p><p>Automatische Boss- und Finsternisregeln sind in Schritt 1 ausgesetzt. Nach jeder Etage steigen Gegner-LP um 15 % und Kontaktschaden um 8 % der Basis.</p><p><b>Pause → Speichern & Hauptmenü</b> sichert die ganze Runde. Freiwilliges Beenden behält verdiente Ressourcen. Automatisch alle 15 Spielsekunden und beim Fensterwechsel gespeichert.</p><p>8 Angriffsslots (Stufe 8), 8 passive Slots (Stufe 8). Nach vollständigem Ausbau: automatische Run-Meisterschaft statt weiterer Kartenpausen.</p></div>`);
  if(page==='characters')this.characterDialog(b.classId);
  if(page==='permanent'||page==='legacy')this.permanentDialog();
  if(page==='codex'){
   const entries=[...WEAPON_IDS.map(id=>({id,info:WEAPONS[id],unlocked:p.weapons.includes(id),type:'Waffe'})),...PASSIVE_IDS.map(id=>({id,info:PASSIVES[id],unlocked:p.passives.includes(id),type:'Passiv'}))];
   this.dialog('Kodex','Bestandsübersicht · Der vollständige Kodex und Entdeckungsfortschritt folgen später.',`<p class="feature-scope">${menuProgress(this.save).upgrades.current} / ${entries.length} Inhalte freigeschaltet. Diese Vorschau zeigt vorhandene Waffen und Passives aus deinem Spielstand. Entdeckungen werden bisher nicht gesondert gespeichert; die Anzeige verwendet deshalb Freischaltungen.</p><div class="codex-preview">${entries.map(e=>`<article class="codex-entry ${e.unlocked?'':'codex-locked'}" data-codex-id="${e.id}">${icon(e.info.icon)}<span><b>${e.info.name}</b><small>${e.type} · ${e.unlocked?'Freigeschaltet':'Gesperrt'}</small></span></article>`).join('')}</div>`,true);
  }
  if(page==='builds')this.dialog('Deine Build-Vorlagen','Ein Startangriff. Der gewählte Pool bestimmt die Angebote im Run. Bis zu 12 Vorlagen.',`<div class="catalog">${p.presets.map((s,i)=>`<article class="catalog-card ${p.selected===i?'selected':''}"><span class="small-label">${CLASSES[s.classId].name}</span><h3>${escape(s.name)}</h3><p>${WEAPONS[s.startWeapon].name}<br>${s.weapons.length} Angriffe · ${s.passives.length} Passives · ${s.masteries.length} Meisterschaften</p><button class="secondary full" data-action="select-preset" data-index="${i}">${p.selected===i?'Ausgewählt':'Auswählen'}</button>${p.selected===i?`<button class="primary full" data-action="edit-preset" data-index="${i}">Bearbeiten</button>`:''}</article>`).join('')}</div>`,true);
  if(page==='expedition')this.dialog('Welten',`${CLASSES[b.classId].name} · ${escape(b.name)} · Start: ${WEAPONS[b.startWeapon].name}`,`<div class="difficulty-list">${DIFFICULTIES.map((d,i)=>`<button class="difficulty ${p.difficulty===i?'selected':''}" data-action="difficulty" data-index="${i}" ${i>p.unlockedDifficulty?'disabled':''}><b>${d.name}</b><span>${d.arena}</span><small>${i>p.unlockedDifficulty?`30-Minuten-Freischaltung in Vorbereitung`:`Gegner-LP ×${d.hp} · Schaden ×${d.damage} · Beute ×${d.reward}`}</small></button>`).join('')}</div><button class="primary full" data-action="start">Durchlauf beginnen</button>`);
  if(page==='stats'){const s=this.save.stats;this.dialog('Deine Chronik',`${s.runs} Runden · ${s.floors} V3-Etagen · ${s.kills} Gegner · Rekord ${formatTime(s.bestTime)} / Level ${s.bestLevel}`,`<div class="history">${this.save.history.length?this.save.history.map(h=>`<div><b>${CLASSES[h.className as ClassId]?.name??escape(h.className)}</b><span>${formatTime(h.time)} · ${h.ending==='retired'?'Beendet':'Gefallen'} · ${DIFFICULTIES[h.difficulty].name}</span><small>${h.kills} Gegner · ${h.floors} Etagen · ${h.gold} Gold · ${h.souls} Fragmente</small></div>`).join(''):'Noch keine abgeschlossene Runde.'}</div>`);}
 }
 private editor(){const d=this.draft!,p=this.save.profile;this.dialog('Build bearbeiten','Nur die Startwaffe ist sofort aktiv. Bis zu 8 Angriffe und 8 Passives werden im Run erworben.',`<label class="editor-label">Name<input id="build-name" maxlength="36" value="${escape(d.name)}"></label><label class="editor-label">Startwaffe<select id="build-start">${p.weapons.filter(id=>WEAPONS[id].class===d.classId||WEAPONS[id].class==='all').map(id=>`<option value="${id}" ${d.startWeapon===id?'selected':''}>${WEAPONS[id].name}</option>`).join('')}</select></label><h3>Angriffspool</h3><div class="check-grid">${p.weapons.filter(id=>WEAPONS[id].class===d.classId||WEAPONS[id].class==='all').map(id=>`<label><input type="checkbox" data-weapon="${id}" ${d.weapons.includes(id)?'checked':''}>${WEAPONS[id].name}</label>`).join('')}</div><h3>Passiver Pool</h3><div class="check-grid">${p.passives.map(id=>`<label><input type="checkbox" data-passive="${id}" ${d.passives.includes(id)?'checked':''}>${PASSIVES[id].name}</label>`).join('')}</div><h3>Meisterschaften · maximal 3</h3><div class="check-grid">${MASTERY_IDS.filter(id=>MASTERIES[id].class===d.classId).map(id=>`<label><input type="checkbox" data-mastery="${id}" ${d.masteries.includes(id)?'checked':''} ${p.masteries[id]===0?'disabled':''}>${MASTERIES[id].name} ${p.masteries[id]}/5</label>`).join('')}</div><button class="primary full" data-action="save-preset">Vorlage speichern</button><button class="secondary full" data-action="copy-preset" ${p.presets.length>=12?'disabled':''}>Als neue Vorlage speichern</button>`,true);}
 private saveDraft(){const d=this.draft!;d.name=(this.root.querySelector('#build-name') as HTMLInputElement).value;d.startWeapon=(this.root.querySelector('#build-start') as HTMLSelectElement).value as WeaponId;d.weapons=[...this.root.querySelectorAll<HTMLInputElement>('[data-weapon]:checked')].map(t=>t.dataset.weapon as WeaponId);d.passives=[...this.root.querySelectorAll<HTMLInputElement>('[data-passive]:checked')].map(t=>t.dataset.passive as PassiveId);d.masteries=[...this.root.querySelectorAll<HTMLInputElement>('[data-mastery]:checked')].map(t=>t.dataset.mastery as MasteryId);}
 startHud(){this.view='playing';this.root.className='game-ui';this.root.innerHTML=`<div class="hud-top"><div class="vitals hud-frame"><div class="vitals-label">${icon('vitality')}<span id="class-name"></span><strong id="hp-text"></strong></div><div class="hp-track"><div id="hp-bar"></div></div><div class="level-row"><span id="level-text"></span><div class="xp-track"><div id="xp-bar"></div></div><span id="xp-text"></span></div><small id="live-stats"></small></div><div class="run-clock"><span id="phase-name"></span><strong id="timer">00:00</strong><span id="phase-timer"></span><small id="resource-text"></small></div><div class="run-count"><div class="kill-counter hud-frame">${icon('ferocity')}<div><span>GEFALLENE</span><strong id="kills">0</strong></div></div><button class="hud-pause hud-frame" data-action="pause" aria-label="Pause (ESC)"><i aria-hidden="true"></i>Pause <span>ESC</span></button></div></div><div id="boss-hud" class="boss-hud" hidden><span id="boss-name"></span><div><i id="boss-bar"></i></div></div><div class="hud-bottom"><div class="arsenal hud-frame"><span class="small-label">ANGRIFFE <small id="mechanic"></small></span><div id="weapons" class="weapon-slots"></div><span class="small-label">PASSIVES</span><div id="passives" class="weapon-slots"></div></div><div class="dash-panel hud-frame"><div class="dash-icon">${icon('speed')}</div><div><span>AUSWEICHSCHRITT</span><div class="dash-track"><i id="dash-bar"></i></div><small id="dash-text"></small></div></div></div><div class="low-hp-vignette" aria-hidden="true"></div><div id="toast" class="toast" role="status"></div><div id="overlay"></div>`;this.lastHud=0;}
 update(e:Engine,force=false){if(!document.getElementById('timer'))return;const now=performance.now();if(!force&&now-this.lastHud<120)return;this.lastHud=now;const set=(id:string,t:string)=>{const n=document.getElementById(id);if(n&&n.textContent!==t)n.textContent=t;};const width=(id:string,v:number)=>{document.getElementById(id)!.style.width=`${Math.max(0,Math.min(100,v))}%`;};set('class-name',CLASSES[e.config.classId].name);set('hp-text',`${Math.ceil(e.player.hp)} / ${e.player.maxHp}`);width('hp-bar',e.player.hp/e.player.maxHp*100);set('level-text',`LV. ${e.level}`);set('xp-text',e.xp>=xpForLevel(e.level)&&e.time<e.nextChoiceAt?`XP gesichert · Wahl in ${Math.ceil(e.nextChoiceAt-e.time)} s`:`${Math.floor(e.xp)}/${xpForLevel(e.level)}`);width('xp-bar',e.xp/xpForLevel(e.level)*100);set('timer',formatTime(Math.ceil(e.floorRemaining)));set('kills',String(e.kills));set('phase-name',`ETAGE ${e.floor}`);set('phase-timer',`${e.floorDuration<180?'SCHNELLTEST · ':''}${DIFFICULTIES[e.config.difficulty].arena} · Gesamt ${formatTime(e.time)}`);set('resource-text',`${Math.floor(e.gold)} Gold · ${e.completedFloors} Etagen geschafft`);set('live-stats',`ATK ×${e.damageMultiplier.toFixed(2)} · DEF ${e.defense} (${Math.round(reduction(e.defense)*100)} %) · Krit ${Math.round(e.criticalChance*100)} %`);set('mechanic',e.config.classId==='warrior'?`Wut ${Math.round(e.rage*100)} %`:e.config.classId==='mage'?`Überladung ${e.casts%6}/6`:'Markierung: 3 Treffer');width('dash-bar',(1-e.player.dashCooldown/e.dashCooldown)*100);this.root.classList.toggle('low-hp',e.player.hp>0&&e.player.hp/e.player.maxHp<.3);this.root.classList.toggle('dash-ready',e.player.dashCooldown<=0);set('dash-text',e.player.dashCooldown>0?`${e.player.dashCooldown.toFixed(1)} s`:'LEERTASTE · BEREIT');
  for(const [host,ids,levels,max] of [['weapons',WEAPON_IDS,e.build.weapons,RULES.weaponMax],['passives',PASSIVE_IDS,e.build.passives,8]] as const){const n=document.getElementById(host)!,key=JSON.stringify(levels);if(n.dataset.build===key)continue;n.dataset.build=key;const equipped=ids.filter(id=>(levels as any)[id]>0);n.innerHTML=equipped.map(id=>`<div class="weapon-slot equipped" title="${id in WEAPONS?WEAPONS[id as WeaponId].name:PASSIVES[id as PassiveId].name} · ${(levels as any)[id]}/${max}">${itemIcon(id)}<span>${(levels as any)[id]}</span>${host==='weapons'?`<i class="weapon-cooldown" id="cd-${id}"></i>`:''}</div>`).join('')+Array.from({length:Math.max(0,8-equipped.length)},()=>'<div class="weapon-slot empty"></div>').join('');}
  for(const id of WEAPON_IDS){const bar=document.getElementById(`cd-${id}`);if(bar)bar.style.width=`${Math.max(0,Math.min(1,1-e.cooldowns[id]/(weaponStats(id,e.build.weapons[id]).cooldown/e.attackSpeed)))*100}%`;}
  const boss=e.boss;document.getElementById('boss-hud')!.hidden=!boss;if(boss){set('boss-name',`${ENEMIES[boss.kind].name} · ${Math.ceil(boss.hp)} LP`);width('boss-bar',boss.hp/boss.maxHp*100);}this.root.classList.toggle('eclipse',e.eclipse);
 }
 overlay(e:Engine){const host=document.getElementById('overlay');if(!host)return;this.view=e.status;if(e.status==='playing'){host.innerHTML='';return;}
  if(e.status==='paused')host.innerHTML=`<div class="overlay-backdrop"><section class="pause-card sa-panel">${eclipseSeal()}<span class="eyebrow">EIN MOMENT DER STILLE</span><h2>Die Nacht wartet.</h2><div class="pause-facts"><span><small>ETAGE</small><b>${e.floor}</b></span><span><small>VERBLEIBEND</small><b>${formatTime(Math.ceil(e.floorRemaining))}</b></span><span><small>LEVEL</small><b>${e.level}</b></span><span><small>GOLD</small><b>${Math.floor(e.gold)}</b></span></div><button class="primary full" data-action="resume">Weiterkämpfen</button><button class="secondary full" data-action="settings">Einstellungen</button><button class="secondary full" data-action="suspend">Speichern & Hauptmenü</button><button class="text-button full" data-action="retire">Runde freiwillig beenden</button><small class="pause-note">Verdiente Ressourcen bleiben bei beiden Optionen erhalten.</small></section></div>`;
  if(e.status==='upgrade')host.innerHTML=`<div class="overlay-backdrop upgrade-backdrop"><section class="upgrade-panel"><span class="eyebrow">LEVEL ${e.level} · +1 LP</span><h2>Die Schatten schenken Macht.</h2><p>Waffen und Talismane aus deinem Kartenpool · Taste <kbd>1</kbd><kbd>2</kbd><kbd>3</kbd> wählt direkt.</p><div class="upgrade-cards">${e.offers.map((o,i)=>{const weapon=o.id in WEAPONS,info=weapon?WEAPONS[o.id as WeaponId]:PASSIVES[o.id as PassiveId],lv=weapon?e.build.weapons[o.id as WeaponId]:e.build.passives[o.id as PassiveId];return `<button class="upgrade-card ${o.rarity}" data-action="upgrade" data-index="${i}" style="--accent:${info.color}"><span class="rarity"><span class="rarity-gem" aria-hidden="true"></span>${o.rarity==='epic'?'EPISCH':o.rarity==='rare'?'SELTEN':'GEWÖHNLICH'}<kbd>${i+1}</kbd></span><div class="upgrade-icon">${itemIcon(o.id)}</div><span class="card-type">${o.recovery?'RUN-MEISTERSCHAFT':weapon?'WAFFENVERBESSERUNG':'PASSIVER TALISMAN'}</span><h3>${o.recovery?'Vermächtnis':info.name}</h3><span class="card-level">${o.recovery?'WIEDERHOLBAR':`STUFE ${lv+1}/${weapon?RULES.weaponMax:RULES.passiveMax}`}</span><p>${upgradeDescription(o,e.build)}</p><div class="card-footer">${o.bonus?`Zusätzlich +${o.bonus} % Run-Schaden`:'Wählen'} →</div></button>`;}).join('')}</div></section></div>`;
  if(e.status==='floorReward')host.innerHTML=`<div class="overlay-backdrop upgrade-backdrop"><section class="upgrade-panel"><span class="eyebrow">ETAGE ${e.floor} ABGESCHLOSSEN</span><h2>Deine Belohnungstruhe</h2><p>Wähle genau einen Bonus. Er gilt für diese Runde und bleibt auf den nächsten Etagen erhalten.</p><div class="upgrade-cards">${e.rewardOffers.map((o,i)=>{const w=o.id in WEAPONS,info=w?WEAPONS[o.id as WeaponId]:PASSIVES[o.id as PassiveId];return `<button class="upgrade-card ${o.rarity}" data-action="reward" data-index="${i}" style="--accent:${info.color}"><span class="rarity"><span class="rarity-gem" aria-hidden="true"></span>${o.rarity==='epic'?'EPISCH':o.rarity==='rare'?'SELTEN':'GEWÖHNLICH'}<kbd>${i+1}</kbd></span><div class="upgrade-icon">${itemIcon(o.id)}</div><span class="card-type">TEMPORÄRER RUN-BONUS</span><h3>${o.recovery?'Run-Meisterschaft':info.name}</h3><p>${upgradeDescription(o,e.build)}</p><div class="card-footer">${o.bonus?`Zusätzlich +${o.bonus} % Run-Schaden`:"Aus der Truhe wählen"} →</div></button>`;}).join('')}</div><button class="secondary" data-action="suspend">Speichern & Hauptmenü</button></section></div>`;
  if(e.status==='floorReady')host.innerHTML=`<div class="overlay-backdrop"><section class="pause-card sa-panel">${eclipseSeal()}<span class="eyebrow">ETAGE ${e.floor} ABGESCHLOSSEN</span><h2>Bereit für Etage ${e.floor+1}?</h2><p>Gewählt: <b>${e.chosenReward?.recovery?'Run-Meisterschaft':e.chosenReward?.id&&e.chosenReward.id in WEAPONS?WEAPONS[e.chosenReward.id as WeaponId].name:e.chosenReward?PASSIVES[e.chosenReward.id as PassiveId].name:''}</b></p><p>Dein Build und ${Math.ceil(e.player.hp)} / ${e.player.maxHp} LP bleiben erhalten. Gegner werden etwas stärker.</p><button class="primary full" data-action="nextFloor">Etage ${e.floor+1} starten</button><button class="secondary full" data-action="suspend">Speichern & Hauptmenü</button><button class="text-button full" data-action="retire">Runde freiwillig beenden</button></section></div>`;
  if(e.status==='dead'||e.status==='retired'){clearTimeout(this.toastTimeout);document.getElementById('toast')?.classList.remove('visible');host.innerHTML=renderRunResult(e);for(const n of this.root.querySelectorAll<HTMLElement>('.hud-top,.hud-bottom,#boss-hud'))n.inert=true;}(host.querySelector<HTMLButtonElement>('button[data-primary]')??host.querySelector<HTMLButtonElement>('button'))?.focus();
 }
 toast(message:string){let n=document.getElementById('toast');if(!n){n=document.createElement('div');n.id='toast';n.className='toast';n.setAttribute('role','status');this.root.append(n);}clearTimeout(this.toastTimeout);n.textContent=message;n.classList.add('visible');this.toastTimeout=setTimeout(()=>n?.classList.remove('visible'),4000);}
}
